experiment:
    project: "selfless-diffusion-0.6B-text2048-finewebedu-adapt"
    name: "text2048-finewebedu-adapt-lr5e-7"
    wandb_project: "unified-mm"
    output_dir: "output"
    save_every: 1000
    eval_every: 100
    generate_every: 10000
    log_every: 10
    log_grad_norm_every: 200
    checkpoints_total_limit: 20
    save_hfmodel_every: 1000
    val_every: 500
    resume_from_checkpoint: none

model:
    model_path: "public/models/Qwen/Qwen3-0.6B-Base"
    attention_pattern: "ar"
    loss_attention_pattern: "likelihood"
    mask_id: -1
    use_flex_attention: true
    lambda_text: 1.0
    lambda_image: 1.0
    continuous_image_latents: true
    image_tokens_per_img: 256
    image_latent_dim: 16
    image_projector_width: 2048
    image_diffusion_depth: 8
    image_diffusion_width: 1280
    image_diffusion_num_sampling_steps: "100"
    image_diffusion_batch_mul: 4
    image_diffusion_condition_norm: "rms"
    image_diffusion_condition_norm_eps: 1.0e-6

dataset:
    class_name: "TextArrowDataset"
    params:
        tokenized_path: "public/.cache/huggingface/datasets/fwb-arrow-eos"
        max_seq_length: 2048
        rows_per_shard: 48804
        pad_to_multiple_of: 64
        sigma_mode: "ar"
        val_ratio: 0.001
        max_val_samples: 1280
    preprocessing:
        max_seq_length: 2048

optimizer:
    name: adamw
    params:
        learning_rate: 5.0e-7
        scale_lr: false
        beta1: 0.9
        beta2: 0.95
        weight_decay: 0.01
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 200
        decay_steps: 3000
        min_lr_scale: 0.2

training:
    batch_size: 8
    total_batch_size: 128
    mixed_precision: "bf16"
    enable_tf32: true
    seed: 42
    dataloader_workers: 4
    max_train_steps: 3000
    max_grad_norm: 1.0
    ar_ratio: -1.0
    mc_samples: 16
    use_gradient_checkpointing: false
    step_scheduler_with_optimizer: false
    from_scratch: false
    freeze_unused_image_modules: true
