#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3/modular_qwen3.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen team, Alibaba Group and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from typing import Callable, Optional, Union

import torch
from torch import nn
from torch.nn import functional as F

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import (
    GenericForQuestionAnswering,
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.models.qwen3.configuration_qwen3 import Qwen3Config
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple
from transformers.utils.deprecation import deprecate_kwarg
from transformers.utils.generic import maybe_autocast, merge_with_config_defaults
from torch.nn.attention.flex_attention import flex_attention, BlockMask, create_block_mask, and_masks
from flash_attn.ops.triton.layer_norm import rms_norm_fn as flash_rms_norm
try:
    from liger_kernel.ops.swiglu import LigerSiLUMulFunction  # noqa: F401
    liger_kernel_is_available = True
except ImportError:
    liger_kernel_is_available = False


def modulate(x, shift, scale):
    return x * (1 + scale) + shift


class FlowTimestepEmbedder(nn.Module):
    def __init__(self, hidden_size, frequency_embedding_size=256):
        super().__init__()
        self.frequency_embedding_size = frequency_embedding_size
        self.mlp = nn.Sequential(
            nn.Linear(frequency_embedding_size, hidden_size, bias=True),
            nn.SiLU(),
            nn.Linear(hidden_size, hidden_size, bias=True),
        )

    @staticmethod
    def timestep_embedding(t, dim, max_period=10000):
        half = dim // 2
        freqs = torch.exp(
            -torch.log(torch.tensor(max_period, device=t.device, dtype=torch.float32))
            * torch.arange(0, half, dtype=torch.float32, device=t.device)
            / half
        )
        args = t[:, None].float() * freqs[None]
        embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
        if dim % 2:
            embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)
        return embedding

    def forward(self, t):
        emb = self.timestep_embedding(t, self.frequency_embedding_size)
        return self.mlp(emb.to(dtype=self.mlp[0].weight.dtype))


class FlowResBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.in_ln = nn.LayerNorm(channels, eps=1e-6)
        self.mlp = nn.Sequential(
            nn.Linear(channels, channels, bias=True),
            nn.SiLU(),
            nn.Linear(channels, channels, bias=True),
        )
        self.adaLN_modulation = nn.Sequential(
            nn.SiLU(),
            nn.Linear(channels, 3 * channels, bias=True),
        )

    def forward(self, x, y):
        shift_mlp, scale_mlp, gate_mlp = self.adaLN_modulation(y).chunk(3, dim=-1)
        h = modulate(self.in_ln(x), shift_mlp, scale_mlp)
        h = self.mlp(h)
        return x + gate_mlp * h


class FlowFinalLayer(nn.Module):
    def __init__(self, model_channels, out_channels):
        super().__init__()
        self.norm_final = nn.LayerNorm(model_channels, elementwise_affine=False, eps=1e-6)
        self.linear = nn.Linear(model_channels, out_channels, bias=True)
        self.adaLN_modulation = nn.Sequential(
            nn.SiLU(),
            nn.Linear(model_channels, 2 * model_channels, bias=True),
        )

    def forward(self, x, c):
        shift, scale = self.adaLN_modulation(c).chunk(2, dim=-1)
        x = modulate(self.norm_final(x), shift, scale)
        return self.linear(x)


class FlowMatchingHead(nn.Module):
    def __init__(
        self,
        target_channels,
        z_channels,
        width=1024,
        depth=3,
        time_scale=1000.0,
        sample_method="heun",
    ):
        super().__init__()
        self.target_channels = target_channels
        self.time_scale = float(time_scale)
        self.sample_method = sample_method
        self.time_embed = FlowTimestepEmbedder(width)
        self.cond_embed = nn.Linear(z_channels, width)
        self.input_proj = nn.Linear(target_channels, width)
        self.res_blocks = nn.ModuleList([FlowResBlock(width) for _ in range(depth)])
        self.final_layer = FlowFinalLayer(width, target_channels)
        self.last_forward_stats = {}
        self.initialize_weights()

    @staticmethod
    def _rms_stat(x):
        return x.detach().float().pow(2).mean().sqrt()

    def initialize_weights(self):
        def _basic_init(module):
            if isinstance(module, nn.Linear):
                torch.nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.constant_(module.bias, 0)
        self.apply(_basic_init)
        nn.init.normal_(self.time_embed.mlp[0].weight, std=0.02)
        nn.init.normal_(self.time_embed.mlp[2].weight, std=0.02)
        for block in self.res_blocks:
            nn.init.constant_(block.adaLN_modulation[-1].weight, 0)
            nn.init.constant_(block.adaLN_modulation[-1].bias, 0)
        nn.init.constant_(self.final_layer.adaLN_modulation[-1].weight, 0)
        nn.init.constant_(self.final_layer.adaLN_modulation[-1].bias, 0)
        nn.init.constant_(self.final_layer.linear.weight, 0)
        nn.init.constant_(self.final_layer.linear.bias, 0)

    def forward(self, target, z, mask=None):
        target = target.float()
        noise = torch.randn_like(target)
        t = torch.rand(target.shape[0], device=target.device, dtype=target.dtype)
        x_t = (1.0 - t[:, None]) * noise + t[:, None] * target
        velocity = target - noise

        pred = self.predict_velocity(x_t, t, z)
        loss = (pred - velocity).pow(2).mean(dim=-1)
        self.last_forward_stats.update(
            {
                "flow/target_rms": self._rms_stat(target),
                "flow/noise_rms": self._rms_stat(noise),
                "flow/velocity_target_rms": self._rms_stat(velocity),
                "flow/mse": loss.detach().float().mean(),
            }
        )
        if mask is not None:
            mask = mask.to(loss.dtype)
            return (loss * mask).sum() / mask.sum().clamp_min(1.0)
        return loss.mean()

    def predict_velocity(self, x_t, t, z):
        model_dtype = self.input_proj.weight.dtype
        z = z.to(dtype=self.cond_embed.weight.dtype)
        x = self.input_proj(x_t.to(dtype=model_dtype))
        scaled_t = t.float() * self.time_scale
        cond = self.cond_embed(z).to(dtype=model_dtype)
        y = self.time_embed(scaled_t).to(dtype=model_dtype) + cond
        for block in self.res_blocks:
            x = block(x, y)
        pred = self.final_layer(x, y).float()
        self.last_forward_stats = {
            "flow/input_xt_rms": self._rms_stat(x_t),
            "flow/hidden_z_rms": self._rms_stat(z),
            "flow/cond_rms": self._rms_stat(cond),
            "flow/time_rms": self._rms_stat(y - cond),
            "flow/y_rms": self._rms_stat(y),
            "flow/pred_velocity_rms": self._rms_stat(pred),
        }
        return pred

    def sample(self, z, num_steps=50, temperature=1.0, sample_method=None, x_init=None):
        sample_method = (sample_method or self.sample_method or "euler").lower()
        if x_init is None:
            x = torch.randn(z.shape[0], self.target_channels, device=z.device, dtype=z.dtype) * temperature
        else:
            x = x_init.to(device=z.device, dtype=z.dtype).clone()
        dt = 1.0 / float(num_steps)
        for step in range(num_steps):
            t = torch.full((z.shape[0],), step / float(num_steps), device=z.device, dtype=torch.float32)
            v = self.predict_velocity(x, t, z).to(dtype=x.dtype)
            if sample_method == "heun":
                x_euler = x + dt * v
                next_t = torch.full(
                    (z.shape[0],),
                    (step + 1) / float(num_steps),
                    device=z.device,
                    dtype=torch.float32,
                )
                next_v = self.predict_velocity(x_euler, next_t, z).to(dtype=x.dtype)
                x = x + 0.5 * dt * (v + next_v)
            elif sample_method == "euler":
                x = x + dt * v
            else:
                raise ValueError(f"Unsupported flow sample_method: {sample_method}")
        return x
    

class ImageLatentProjector(nn.Module):
    def __init__(self, latent_dim, hidden_size, projector_width=None):
        super().__init__()
        projector_width = int(projector_width or hidden_size * 2)
        self.in_norm = nn.LayerNorm(latent_dim, eps=1e-6)
        self.fc1 = nn.Linear(latent_dim, projector_width, bias=True)
        self.act = nn.GELU()
        self.fc2 = nn.Linear(projector_width, hidden_size, bias=True)
        self.out_norm = nn.LayerNorm(hidden_size, eps=1e-6)

    @property
    def weight_dtype(self):
        return self.fc1.weight.dtype

    def forward(self, latents):
        x = latents.to(dtype=self.in_norm.weight.dtype)
        x = self.in_norm(x).to(dtype=self.fc1.weight.dtype)
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        return self.out_norm(x)


def _compute_default_rope_parameters(config: Qwen3Config, device=None):
    base = getattr(config, "rope_theta", 10000.0)
    head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
    partial_rotary_factor = getattr(config, "partial_rotary_factor", 1.0)
    dim = int(head_dim * partial_rotary_factor)
    inv_freq = 1.0 / (
        base ** (torch.arange(0, dim, 2, dtype=torch.float32, device=device) / dim)
    )
    return inv_freq, 1.0


@use_kernel_forward_from_hub("RMSNorm")
class Qwen3RMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        Qwen3RMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        return flash_rms_norm(
            hidden_states, weight=self.weight, bias=None, eps=self.variance_epsilon)
        '''
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * \
            torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)
        '''

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class Qwen3MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(
            self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        if liger_kernel_is_available:
            return self.down_proj(LigerSiLUMulFunction.apply(self.gate_proj(x), self.up_proj(x)))
        else:
            down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
            return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(X0_q, XT_q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    X0_q_embed = (X0_q * cos) + (rotate_half(X0_q) * sin)
    XT_q_embed = (XT_q * cos) + (rotate_half(XT_q) * sin) if XT_q is not None else None
    k_embed = (k * cos) + (rotate_half(k) * sin)
    
    return X0_q_embed, XT_q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


@torch.compile(fullgraph=True, mode="max-autotune-no-cudagraphs")
def compiled_flex_attention(query, key, value, attention_mask, scaling, enable_gqa):
    """编译优化的 flex_attention 包装函数"""
    return flex_attention(
        query=query,
        key=key,
        value=value,
        score_mod=None,
        block_mask=attention_mask,
        scale=scaling,
        enable_gqa=enable_gqa,
        return_lse=False,
    )

@torch.compile(
    fullgraph=True,
    mode="default",
    dynamic=True
)
def dynamic_flex_attention(query, key, value, attention_mask, scaling, enable_gqa):
    """自适应tokens长度的 flex_attention 包装函数"""
    return flex_attention(
        query=query,
        key=key,
        value=value,
        score_mod=None,
        block_mask=attention_mask,
        scale=scaling,
        enable_gqa=enable_gqa,
        return_lse=False,
    )

    
class Qwen3Attention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: Qwen3Config, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        self.q_norm = Qwen3RMSNorm(self.head_dim, eps=config.rms_norm_eps)  # unlike olmo, only on the head dim!
        self.k_norm = Qwen3RMSNorm(self.head_dim, eps=config.rms_norm_eps)  # thus post q_norm does not need reshape

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: BlockMask,
        past_key_values: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        input_shape = X0_hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)
            
        XT_query_states = self.q_norm(self.q_proj(XT_hidden_states).view(hidden_shape)).transpose(1, 2) if XT_hidden_states is not None else None
        
        X0_query_states = self.q_norm(self.q_proj(X0_hidden_states).view(hidden_shape)).transpose(1, 2)
        X0_key_states = self.k_norm(self.k_proj(X0_hidden_states).view(hidden_shape)).transpose(1, 2)
        X0_value_states = self.v_proj(X0_hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        X0_query_states, XT_query_states, X0_key_states,  = apply_rotary_pos_emb(X0_query_states, XT_query_states, X0_key_states, cos, sin)

        if past_key_values is not None:
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            X0_key_states, X0_value_states = past_key_values.update(X0_key_states, X0_value_states, self.layer_idx, cache_kwargs)
        
        # 检查是否需要 GQA (Grouped Query Attention)
        enable_gqa = self.config.num_attention_heads != self.config.num_key_value_heads
        
        if self.training == False:
            X0_attn_output = dynamic_flex_attention(
                query=X0_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            )
            XT_attn_output = dynamic_flex_attention(
                query=XT_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            ) if XT_query_states is not None else None
            attn_weights = None
        else:
            # 调用 flex_attention
            X0_attn_output = compiled_flex_attention(
                query=X0_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            )
            XT_attn_output = compiled_flex_attention(
                query=XT_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            ) if XT_query_states is not None else None
            attn_weights = None
        
        # attn_output 形状: (batch, heads, seq_len, head_dim)
        # 需要转换回 (batch, seq_len, hidden_size)
        X0_attn_output = X0_attn_output.transpose(1, 2).reshape(*input_shape, -1).contiguous()
        XT_attn_output = XT_attn_output.transpose(1, 2).reshape(*input_shape, -1).contiguous() if XT_attn_output is not None else None
        X0_attn_output = self.o_proj(X0_attn_output)
        XT_attn_output = self.o_proj(XT_attn_output) if XT_attn_output is not None else None
        
        return X0_attn_output, XT_attn_output, attn_weights


class Qwen3DecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: Qwen3Config, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = Qwen3Attention(config=config, layer_idx=layer_idx)

        self.mlp = Qwen3MLP(config)
        self.input_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.attention_type = config.layer_types[layer_idx]

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor,
        attention_mask: BlockMask,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        X0_residual = X0_hidden_states
        XT_residual = XT_hidden_states if XT_hidden_states is not None else None
        X0_hidden_states = self.input_layernorm(X0_hidden_states)
        XT_hidden_states = self.input_layernorm(XT_hidden_states) if XT_hidden_states is not None else None
        # Self Attention
        X0_hidden_states, XT_hidden_states, _ = self.self_attn(
            X0_hidden_states=X0_hidden_states,
            XT_hidden_states=XT_hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        X0_hidden_states = X0_residual + X0_hidden_states
        XT_hidden_states = XT_residual + XT_hidden_states if XT_hidden_states is not None else None

        # Fully Connected
        X0_residual = X0_hidden_states
        XT_residual = XT_hidden_states if XT_hidden_states is not None else None
        X0_hidden_states = self.post_attention_layernorm(X0_hidden_states)
        XT_hidden_states = self.post_attention_layernorm(XT_hidden_states) if XT_hidden_states is not None else None
        X0_hidden_states = self.mlp(X0_hidden_states)
        XT_hidden_states = self.mlp(XT_hidden_states) if XT_hidden_states is not None else None
        X0_hidden_states = X0_residual + X0_hidden_states
        XT_hidden_states = XT_residual + XT_hidden_states if XT_hidden_states is not None else None
        return X0_hidden_states, XT_hidden_states


@auto_docstring
class Qwen3PreTrainedModel(PreTrainedModel):
    config: Qwen3Config
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["Qwen3DecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": Qwen3DecoderLayer,
        "attentions": Qwen3Attention,
    }


class Qwen3RotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    @staticmethod
    def compute_default_rope_parameters(config: Qwen3Config, device=None):
        return _compute_default_rope_parameters(config, device)

    def __init__(self, config: Qwen3Config, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and isinstance(config.rope_scaling, dict):
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        if self.rope_type in (None, "default"):
            self.rope_init_fn = ROPE_INIT_FUNCTIONS.get("default", _compute_default_rope_parameters)
        else:
            self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class Qwen3Model(Qwen3PreTrainedModel):
    def __init__(self, config: Qwen3Config):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.image_latent_dim = getattr(config, "image_latent_dim", 4)
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.image_latent_proj = ImageLatentProjector(
            self.image_latent_dim,
            config.hidden_size,
            getattr(config, "image_projector_width", None),
        )
        self.layers = nn.ModuleList(
            [Qwen3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = Qwen3RotaryEmbedding(config=config)
        self.gradient_checkpointing = False
        self.XT_input_ids = None

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, new_embeddings):
        self.embed_tokens = new_embeddings

    # @check_model_inputs
    @auto_docstring
    def forward(
        self,
        X0_input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[BlockMask] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        X0_inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        calculate_likelihood: Optional[bool] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        r"""
        Args:
            X0_input_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Indices of input sequence tokens in the vocabulary.
            attention_mask (`BlockMask`, *optional*):
                Attention mask for Flex Attention. Should be a block mask of shape `(batch_size, sequence_length)`.
            calculate_likelihood (`bool`, *optional*):
                Whether to calculate the likelihood of the input sequence. If `True`, the model will compute the likelihood using the XT stream, which is necessary for training. If `False`, the model will only compute the hidden states for the X0 stream, which can be used for efficient decoding.
        """
        if (X0_input_ids is None) ^ (X0_inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")
        if attention_mask is None:
            raise ValueError("attention_mask must be provided for diffusion-causal attention.")

        if X0_inputs_embeds is None:
            token_types = kwargs.get("token_types", None)
            if token_types is None:
                X0_inputs_embeds = self.embed_tokens(X0_input_ids)
            else:
                token_types = token_types.to(X0_input_ids.device)
                image_latents = kwargs.get("image_latents", None)
                image_latent_mask = kwargs.get("image_latent_mask", None)
                is_image = token_types == 1
                safe_input_ids = X0_input_ids.masked_fill(is_image, self.config.mask_token_id)
                X0_inputs_embeds = self.embed_tokens(safe_input_ids)
                if is_image.any():
                    if image_latents is None:
                        raise ValueError("image_latents must be provided when token_types contains image tokens.")
                    if image_latents.shape[-1] != self.image_latent_dim:
                        raise ValueError(
                            f"image_latents last dimension ({image_latents.shape[-1]}) must match "
                            f"config.image_latent_dim ({self.image_latent_dim})."
                        )
                    image_latents = image_latents.to(device=X0_input_ids.device, dtype=self.image_latent_proj.weight_dtype)
                    use_image_latent = is_image
                    if image_latent_mask is not None:
                        image_latent_mask = image_latent_mask.to(device=X0_input_ids.device, dtype=torch.bool)
                        use_image_latent = is_image & image_latent_mask
                    if use_image_latent.any():
                        X0_inputs_embeds[use_image_latent] = self.image_latent_proj(image_latents[use_image_latent])
                elif self.training:
                    dummy_latent = torch.zeros(
                        1,
                        self.image_latent_dim,
                        device=X0_input_ids.device,
                        dtype=self.image_latent_proj.weight_dtype,
                    )
                    X0_inputs_embeds = X0_inputs_embeds + self.image_latent_proj(dummy_latent).sum() * 0.0

        if self.training or calculate_likelihood:
            if self.XT_input_ids is None or self.XT_input_ids.shape != X0_input_ids.shape:
                self.XT_input_ids = torch.full_like(X0_input_ids, self.config.mask_token_id)
            # XT stream: mask tokens use text embedding (XT always gets [MASK] embeddings)
            XT_inputs_embeds = self.embed_tokens(self.XT_input_ids)
        else:
            self.XT_input_ids = None
            XT_inputs_embeds = None

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + X0_inputs_embeds.shape[1], device=X0_inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        X0_hidden_states = X0_inputs_embeds
        XT_hidden_states = XT_inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(X0_hidden_states, position_ids)
        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            X0_hidden_states, XT_hidden_states = decoder_layer(
                X0_hidden_states,
                XT_hidden_states,
                attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )

        if self.training or calculate_likelihood:
            XT_hidden_states = self.norm(XT_hidden_states)
            return BaseModelOutputWithPast(
                last_hidden_state=XT_hidden_states,
                past_key_values=past_key_values if use_cache else None,
            )
        else:
            X0_hidden_states = self.norm(X0_hidden_states)
            return BaseModelOutputWithPast(
                last_hidden_state=X0_hidden_states,
                past_key_values=past_key_values if use_cache else None,
            )


@auto_docstring
class Qwen3ForCausalLM(Qwen3PreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = Qwen3Model(config)
        self.vocab_size = config.vocab_size
        self.image_latent_dim = getattr(config, "image_latent_dim", 4)
        self.unified_head = False
        self.lambda_image = getattr(config, "lambda_image", 0.5)
        self.lambda_text = getattr(config, "lambda_text", 1.0)

        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self.flow_head = FlowMatchingHead(
            target_channels=self.image_latent_dim,
            z_channels=config.hidden_size,
            width=getattr(config, "flow_width", config.hidden_size),
            depth=getattr(config, "flow_depth", 3),
            time_scale=getattr(config, "flow_time_scale", 1000.0),
            sample_method=getattr(config, "flow_sample_method", "heun"),
        )

        # Initialize weights and apply final processing
        self.post_init()

    def tie_weights(self, missing_keys: set[str] | None = None, recompute_mapping: bool = True):
        # Delegate standard tie (lm_head ↔ embed_tokens) to parent
        super().tie_weights(missing_keys=missing_keys, recompute_mapping=recompute_mapping)

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        X0_input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[BlockMask] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        image_latents: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        calculate_likelihood: bool = False,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        r"""
        Args:
            X0_input_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Indices of input sequence tokens in the vocabulary. The input sequence should be formatted as
                `[X0_1, X0_2, ..., X0_n]`, where `X0_i` represents the tokens at diffusion time step 0 for the i-th
                position. All tokens in `X0_input_ids` should have the same diffusion time step (i.e., all should be
                from the same "diffusion slice"). If `inputs_embeds` is not provided, this argument will be used to
                compute the input embeddings.
            attention_mask (`BlockMask`, *optional*):
                Attention mask for diffusion-causal attention. Should be a block mask of shape `(batch_size,
                sequence_length)` where each block corresponds to a diffusion time step. The mask should be designed
                such that tokens can only attend to tokens from the same or earlier diffusion time steps, and not to
                tokens from later diffusion time steps.
            labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Labels for language modeling. Tokens with labels set to -100 will be ignored when computing the loss.
            image_latents (`torch.FloatTensor` of shape `(batch_size, sequence_length, image_latent_dim)`, *optional*):
                Continuous VAE latent tokens aligned with `token_types == 1` positions.
            calculate_likelihood (`bool`, *optional*, defaults to `False`):
                Whether to calculate the likelihood of the input sequence. If `True`, the model will compute the likelihood using the XT stream, which is necessary for training. If `False`, the model will only compute the hidden states for the X0 stream, which can be used for efficient decoding. Note that when `calculate_likelihood` is `True`, the model will return the likelihood loss in the `loss` field of the output, and the `logits` field will contain the logits from the XT stream.
        ```"""
        calculate_likelihood = calculate_likelihood or labels is not None
        outputs: BaseModelOutputWithPast = self.model(
            X0_input_ids=X0_input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            calculate_likelihood=calculate_likelihood,
            image_latents=image_latents,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep

        token_types = kwargs.get("token_types", None)
        logits = None
        if not (labels is not None and token_types is not None):
            logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            if token_types is not None:
                token_types = token_types.to(hidden_states.device)
                text_mask = (token_types == 0) | (token_types == 2)
                image_mask = token_types == 1

                flat_hidden = hidden_states.view(-1, hidden_states.size(-1))
                flat_labels = labels.view(-1)

                text_flat_mask = text_mask.view(-1)
                image_flat_mask = image_mask.view(-1)

                text_loss = flat_hidden.sum() * 0.0
                valid_text_mask = text_flat_mask & (flat_labels != -100)
                if valid_text_mask.any():
                    text_logits = self.lm_head(flat_hidden[valid_text_mask])
                    text_loss = F.cross_entropy(
                        text_logits, flat_labels[valid_text_mask], ignore_index=-100
                    )

                if image_flat_mask.any():
                    if image_latents is None:
                        raise ValueError("image_latents must be provided for continuous image flow loss.")
                    if image_latents.shape[-1] != self.image_latent_dim:
                        raise ValueError(
                            f"image_latents last dimension ({image_latents.shape[-1]}) must match "
                            f"config.image_latent_dim ({self.image_latent_dim})."
                        )
                    flat_image_latents = image_latents.to(hidden_states.device).view(-1, self.image_latent_dim)
                    image_loss = self.flow_head(
                        target=flat_image_latents[image_flat_mask],
                        z=flat_hidden[image_flat_mask],
                    )
                else:
                    dummy_target = torch.zeros(1, self.image_latent_dim, device=hidden_states.device)
                    dummy_hidden = flat_hidden[:1]
                    image_loss = self.flow_head(dummy_target, dummy_hidden) * 0.0

                loss = self.lambda_text * text_loss + self.lambda_image * image_loss
            else:
                loss = self.loss_function(
                    logits.view(-1, logits.size(-1)), labels.view(-1), ignore_index=-100
                )

        output = CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )
        output.last_hidden_state = hidden_states
        # Attach per-modality losses for logging
        if token_types is not None and loss is not None:
            output.per_modality_loss = {
                "text_loss": text_loss.detach() if isinstance(text_loss, torch.Tensor) else torch.tensor(text_loss or 0.0, device=hidden_states.device),
                "image_loss": image_loss.detach() if isinstance(image_loss, torch.Tensor) else torch.tensor(image_loss or 0.0, device=hidden_states.device),
            }
            output.flow_debug_stats = {
                key: value.detach()
                for key, value in self.flow_head.last_forward_stats.items()
                if isinstance(value, torch.Tensor)
            }
        return output
        
    @torch.compile(mode="max-autotune-no-cudagraphs")
    def loss_function(self, logits, labels, ignore_index, reduction='mean'):
        return F.cross_entropy(logits.view(-1, logits.size(-1)), labels.view(-1), ignore_index=ignore_index, reduction=reduction)

    @torch.no_grad()
    def sample_image_latents_single_stream(
        self,
        input_ids: torch.Tensor,
        token_types: torch.Tensor,
        sigma: torch.Tensor,
        spans: list[tuple[int, int, int]],
        image_latent_dim: int | None = None,
        flow_steps: int = 50,
        flow_temperature: float = 1.0,
        flow_sample_method: str | None = None,
        parallel_rate: int = 32,
        order_strategy: str = "condition_norm",
        return_trace: bool = False,
    ) -> torch.Tensor | tuple[torch.Tensor | None, dict[str, torch.Tensor | str]] | None:
        from utils.utils import get_selfless_mask

        if not spans:
            return (None, {}) if return_trace else None

        device = input_ids.device
        image_latent_dim = image_latent_dim or self.image_latent_dim
        image_tokens_per_img = int(getattr(self.config, "image_tokens_per_img", 256))
        side = int(image_tokens_per_img ** 0.5)
        if side * side != image_tokens_per_img:
            raise ValueError(f"image_tokens_per_img={image_tokens_per_img} is not square")
        selected_input_ids = torch.stack([input_ids[b] for b, _, _ in spans]).to(device=device)
        selected_token_types = torch.stack([token_types[b] for b, _, _ in spans]).to(device=device)
        selected_sigma = torch.stack([sigma[b] for b, _, _ in spans]).to(device=device, dtype=torch.float32)
        work_latents = torch.zeros(
            selected_input_ids.shape[0],
            selected_input_ids.shape[1],
            image_latent_dim,
            device=device,
            dtype=self.flow_head.final_layer.linear.weight.dtype,
        )

        original_orders = []
        local_spans = []
        for out_idx, (batch_idx, start, end) in enumerate(spans):
            local_spans.append((out_idx, start, end))
            original_orders.append(torch.argsort(sigma[batch_idx, start:end].to(device=device, dtype=torch.float32)))

        def _halton(index: int, base: int) -> float:
            value = 0.0
            scale = 1.0 / float(base)
            while index > 0:
                value += (index % base) * scale
                index //= base
                scale /= float(base)
            return value

        def _halton_order() -> torch.Tensor:
            seen = set()
            order = []
            idx = 1
            while len(order) < image_tokens_per_img and idx < image_tokens_per_img * 32:
                row = min(side - 1, int(_halton(idx, 2) * side))
                col = min(side - 1, int(_halton(idx, 3) * side))
                flat = row * side + col
                if flat not in seen:
                    seen.add(flat)
                    order.append(flat)
                idx += 1
            if len(order) < image_tokens_per_img:
                order.extend([flat for flat in range(image_tokens_per_img) if flat not in seen])
            return torch.tensor(order, device=device, dtype=torch.long)

        def _spatial_uniform_order() -> torch.Tensor:
            yy, xx = torch.meshgrid(
                torch.arange(side, device=device),
                torch.arange(side, device=device),
                indexing="ij",
            )
            center = (side - 1) / 2.0
            ring = torch.maximum((yy.float() - center).abs(), (xx.float() - center).abs())
            checker = (yy % 2) * 2 + (xx % 2)
            return torch.argsort((ring * 4.0 + checker.float()).flatten())

        filled = torch.zeros(
            len(spans),
            image_tokens_per_img,
            device=device,
            dtype=torch.bool,
        )
        generated = torch.zeros(
            len(spans),
            image_tokens_per_img,
            image_latent_dim,
            device=device,
            dtype=work_latents.dtype,
        )
        generation_order = torch.zeros(
            len(spans),
            image_tokens_per_img,
            device=device,
            dtype=torch.long,
        )
        generation_step = torch.zeros_like(generation_order)
        generation_score = torch.zeros(
            len(spans),
            image_tokens_per_img,
            device=device,
            dtype=torch.float32,
        )

        current_sigma = selected_sigma.clone()
        next_image_order = torch.zeros(len(spans), device=device, dtype=torch.float32)
        k = max(1, int(parallel_rate))
        order_strategy = str(order_strategy or "condition_norm").lower()
        replay_original_sigma = order_strategy in {"sigma", "sigma_replay"}
        if not replay_original_sigma:
            for sample_idx, start, end in local_spans:
                original_image_sigma = selected_sigma[sample_idx, start:end]
                start_order = float(original_image_sigma.min().item())
                visible_context = (
                    (selected_token_types[sample_idx] != 1)
                    & (selected_token_types[sample_idx] != 3)
                    & (selected_sigma[sample_idx] < start_order)
                )
                if visible_context.any():
                    start_order = max(
                        start_order,
                        float(selected_sigma[sample_idx, visible_context].max().item() + 1.0),
                    )
                next_image_order[sample_idx] = start_order
                current_sigma[sample_idx, start:end] = start_order + image_tokens_per_img
        fill_counter = torch.ones(len(spans), device=device, dtype=torch.long)
        step_idx = 1
        fixed_orders = {
            "spatial_halton": _halton_order(),
            "halton": _halton_order(),
            "spatial_uniform": _spatial_uniform_order(),
            "uniform": _spatial_uniform_order(),
        }
        latent_level_strategies = {"latent_proj_cosine", "flow_self_consistency", "solver_consistency"}

        while not filled.all():
            attention_mask = get_selfless_mask(
                sigma=current_sigma,
                seq_len=selected_input_ids.shape[1],
                device=device,
            )
            image_latent_mask = torch.zeros_like(selected_token_types, dtype=torch.bool)
            for sample_idx, start, _ in local_spans:
                image_latent_mask[sample_idx, start : start + image_tokens_per_img] = filled[sample_idx]
            hidden = self.model(
                X0_input_ids=selected_input_ids,
                attention_mask=attention_mask,
                token_types=selected_token_types,
                image_latents=work_latents,
                image_latent_mask=image_latent_mask,
                calculate_likelihood=False,
            ).last_hidden_state

            fill_local_positions = []
            if order_strategy in latent_level_strategies:
                all_sample_indices = []
                all_seq_positions = []
                all_local_positions = []
                candidate_counts = []
                for sample_idx, start, _ in local_spans:
                    remaining = (~filled[sample_idx]).nonzero(as_tuple=True)[0]
                    candidate_counts.append(int(remaining.numel()))
                    if remaining.numel() == 0:
                        continue
                    all_sample_indices.append(torch.full_like(remaining, sample_idx))
                    all_seq_positions.append(start + remaining)
                    all_local_positions.append(remaining)

                if not all_sample_indices:
                    break

                all_sample_indices = torch.cat(all_sample_indices)
                all_seq_positions = torch.cat(all_seq_positions)
                all_local_positions = torch.cat(all_local_positions)
                z = hidden[all_sample_indices, all_seq_positions]

                if order_strategy == "solver_consistency":
                    noise = torch.randn(
                        z.shape[0],
                        self.flow_head.target_channels,
                        device=device,
                        dtype=z.dtype,
                    ) * flow_temperature
                    candidate_pred = self.flow_head.sample(
                        z,
                        num_steps=flow_steps,
                        temperature=flow_temperature,
                        sample_method=flow_sample_method,
                        x_init=noise,
                    ).to(work_latents.dtype)
                    fast_steps = max(4, int(flow_steps) // 2)
                    default_method = str(flow_sample_method or self.flow_head.sample_method or "euler").lower()
                    fast_method = "euler" if default_method == "heun" else default_method
                    fast_pred = self.flow_head.sample(
                        z,
                        num_steps=fast_steps,
                        temperature=flow_temperature,
                        sample_method=fast_method,
                        x_init=noise,
                    ).to(work_latents.dtype)
                    all_scores = -(candidate_pred.float() - fast_pred.float()).pow(2).mean(dim=-1).sqrt()
                elif order_strategy == "flow_self_consistency":
                    noise = torch.randn(
                        z.shape[0],
                        self.flow_head.target_channels,
                        device=device,
                        dtype=z.dtype,
                    ) * flow_temperature
                    candidate_pred = self.flow_head.sample(
                        z,
                        num_steps=flow_steps,
                        temperature=flow_temperature,
                        sample_method=flow_sample_method,
                        x_init=noise,
                    ).to(work_latents.dtype)
                    t_mid = torch.full((z.shape[0],), 0.5, device=device, dtype=torch.float32)
                    x_mid = 0.5 * noise.to(candidate_pred.dtype) + 0.5 * candidate_pred
                    target_velocity = candidate_pred.float() - noise.float()
                    pred_velocity = self.flow_head.predict_velocity(x_mid, t_mid, z).float()
                    all_scores = -(pred_velocity - target_velocity).pow(2).mean(dim=-1)
                else:
                    candidate_pred = self.flow_head.sample(
                        z,
                        num_steps=flow_steps,
                        temperature=flow_temperature,
                        sample_method=flow_sample_method,
                    ).to(work_latents.dtype)
                    projected = self.model.image_latent_proj(
                        candidate_pred.to(dtype=self.model.image_latent_proj.weight_dtype)
                    )
                    all_scores = F.cosine_similarity(projected.float(), z.float(), dim=-1)

                cursor = 0
                for sample_idx, count in enumerate(candidate_counts):
                    if count == 0:
                        continue
                    local_positions = all_local_positions[cursor : cursor + count]
                    local_scores = all_scores[cursor : cursor + count]
                    local_pred = candidate_pred[cursor : cursor + count]
                    fill_count = min(k, count)
                    scores, chosen = torch.topk(local_scores, k=fill_count, dim=-1)
                    positions = local_positions[chosen]
                    chunks = local_pred[chosen]
                    fill_local_positions.append((sample_idx, positions, scores, chunks))
                    cursor += count
            else:
                for sample_idx, start, _ in local_spans:
                    remaining_mask = ~filled[sample_idx]
                    remaining_count = int(remaining_mask.sum().item())
                    if remaining_count == 0:
                        continue
                    fill_count = min(k, remaining_count)

                    if order_strategy in {"sigma", "sigma_replay", "causal_sigma"}:
                        order = original_orders[sample_idx]
                        positions = order[~filled[sample_idx, order]][:fill_count]
                        scores = -sigma[spans[sample_idx][0], spans[sample_idx][1] : spans[sample_idx][2]].to(
                            device=device, dtype=torch.float32
                        )[positions]
                    elif order_strategy == "random":
                        remaining = remaining_mask.nonzero(as_tuple=True)[0]
                        positions = remaining[torch.randperm(remaining.numel(), device=device)[:fill_count]]
                        scores = torch.ones(fill_count, device=device, dtype=torch.float32)
                    elif order_strategy in fixed_orders:
                        order = fixed_orders[order_strategy]
                        positions = order[~filled[sample_idx, order]][:fill_count]
                        scores = torch.arange(fill_count, 0, -1, device=device, dtype=torch.float32)
                    elif order_strategy in {"condition_norm", "hidden_norm", "confidence"}:
                        span_hidden = hidden[sample_idx, start : start + image_tokens_per_img]
                        all_scores = span_hidden.detach().float().pow(2).mean(dim=-1).sqrt()
                        all_scores = all_scores.masked_fill(~remaining_mask, -torch.inf)
                        scores, positions = torch.topk(all_scores, k=fill_count, dim=-1)
                    else:
                        raise ValueError(
                            f"Unknown single-stream order_strategy={order_strategy!r}; "
                            "expected one of: hidden_norm, latent_proj_cosine, flow_self_consistency, "
                            "solver_consistency, spatial_halton, spatial_uniform, sigma, causal_sigma, random."
                        )

                    fill_local_positions.append((sample_idx, positions, scores, None))

            if not fill_local_positions:
                break

            if order_strategy not in latent_level_strategies:
                sample_indices = []
                seq_positions = []
                for sample_idx, positions, _, _ in fill_local_positions:
                    sample_indices.append(torch.full_like(positions, sample_idx))
                    seq_positions.append(local_spans[sample_idx][1] + positions)
                sample_indices = torch.cat(sample_indices)
                seq_positions = torch.cat(seq_positions)

                z = hidden[sample_indices, seq_positions]
                pred = self.flow_head.sample(
                    z,
                    num_steps=flow_steps,
                    temperature=flow_temperature,
                    sample_method=flow_sample_method,
                ).to(work_latents.dtype)

            cursor = 0
            for sample_idx, local_positions, local_scores, local_chunks in fill_local_positions:
                count = local_positions.numel()
                if local_chunks is None:
                    chunk = pred[cursor:cursor + count]
                    cursor += count
                else:
                    chunk = local_chunks
                start = local_spans[sample_idx][1]
                work_latents[sample_idx, start + local_positions] = chunk
                generated[sample_idx, local_positions] = chunk
                filled[sample_idx, local_positions] = True
                if not replay_original_sigma:
                    new_sigma = next_image_order[sample_idx] + torch.arange(
                        count,
                        device=device,
                        dtype=current_sigma.dtype,
                    )
                    current_sigma[sample_idx, start + local_positions] = new_sigma
                    next_image_order[sample_idx] += float(count)
                start_count = int(fill_counter[sample_idx].item())
                generation_order[sample_idx, local_positions] = torch.arange(
                    start_count,
                    start_count + count,
                    device=device,
                    dtype=generation_order.dtype,
                )
                generation_step[sample_idx, local_positions] = step_idx
                generation_score[sample_idx, local_positions] = local_scores.to(generation_score.dtype)
                fill_counter[sample_idx] += count
            step_idx += 1

        generated = generated.view(len(spans), side, side, image_latent_dim).permute(0, 3, 1, 2)
        if return_trace:
            trace = {
                "order_strategy": order_strategy,
                "generation_order": generation_order.view(len(spans), side, side),
                "generation_step": generation_step.view(len(spans), side, side),
                "generation_score": generation_score.view(len(spans), side, side),
            }
            return generated, trace
        return generated

    def _image_logits_from_hidden(self, hidden_states: torch.Tensor) -> torch.Tensor:
        raise NotImplementedError("Continuous image flow model does not expose VQ image logits.")

    def _sample_from_logits(self, logits: torch.Tensor, temperature: float) -> tuple[torch.Tensor, torch.Tensor]:
        if temperature < 1e-6:
            probs = torch.softmax(logits, dim=-1)
            next_token = logits.argmax(dim=-1)
        else:
            probs = torch.softmax(logits / temperature, dim=-1)
            next_token = torch.multinomial(probs, 1).squeeze(-1)
        conf = probs.gather(-1, next_token.unsqueeze(-1)).squeeze(-1)
        return next_token, conf

    def _select_fill_mask(self, conf: torch.Tensor, valid_mask: torch.Tensor, ratio, parallel_rate, decode_strategy: str) -> torch.Tensor:
        masked_conf = conf.masked_fill(~valid_mask, -1.0)
        fill_mask = torch.zeros_like(valid_mask, dtype=torch.bool)
        if not valid_mask.any():
            return fill_mask

        if decode_strategy == "random":
            k = 1 if parallel_rate is None else max(1, min(int(parallel_rate), int(valid_mask.sum().item())))
            cols = torch.multinomial(valid_mask.float(), num_samples=k, replacement=False)
            fill_mask[cols] = True
            return fill_mask

        if decode_strategy != "confidence":
            raise ValueError(f"Unknown decode_strategy: {decode_strategy}")

        if parallel_rate is not None:
            k = max(1, min(int(parallel_rate), int(valid_mask.sum().item())))
            _, cols = torch.topk(masked_conf, k=k, dim=-1)
            fill_mask[cols] = True
        elif ratio is not None:
            fill_mask = masked_conf >= ratio
            if not fill_mask.any():
                fill_mask[masked_conf.argmax(dim=-1)] = True
        else:
            fill_mask[masked_conf.argmax(dim=-1)] = True
        return fill_mask

    @torch.no_grad()
    def _generate_one(
        self,
        prompt_ids: torch.Tensor,
        gen_length: int,
        prompt_task: str,
        block_size: int,
        temperature: float,
        ratio,
        parallel_rate,
        decode_strategy: str,
    ) -> tuple[torch.Tensor, torch.Tensor, int, int]:
        from utils.utils import get_selfless_mask

        device = self.device
        image_tokens_per_img = getattr(self.config, "image_tokens_per_img", 256)
        boi_token_id = getattr(self.config, "boi_token_id", None)
        eoi_token_id = getattr(self.config, "eoi_token_id", None)
        eos_token_id = getattr(self.config, "eos_token_id", None)
        if boi_token_id is None or eoi_token_id is None:
            raise ValueError("boi_token_id and eoi_token_id must be set for multimodal generation.")

        seq = prompt_ids.to(device=device, dtype=torch.long).flatten().clone()
        token_types = torch.zeros_like(seq, dtype=torch.uint8)
        sigma = torch.empty(seq.shape[0], dtype=torch.float32, device=device)
        if prompt_task == "ar":
            sigma[:] = torch.arange(seq.shape[0], device=device, dtype=sigma.dtype)
        elif prompt_task == "diffusion":
            sigma[:] = torch.rand(seq.shape[0], device=device, dtype=sigma.dtype)
        else:
            raise ValueError(f"Invalid prompt task: {prompt_task}")

        generated_text_tokens = 0
        image_fill_steps = 0
        image_tokens_filled = 0

        def next_sigma_values(n: int) -> torch.Tensor:
            start = float(sigma.max().item() + 1.0) if sigma.numel() > 0 else 0.0
            return torch.arange(start, start + n, device=device, dtype=sigma.dtype)

        while generated_text_tokens < gen_length:
            seq = torch.cat([seq, torch.tensor([self.config.mask_token_id], device=device, dtype=torch.long)])
            token_types = torch.cat([token_types, torch.tensor([0], device=device, dtype=torch.uint8)])
            sigma = torch.cat([sigma, next_sigma_values(1)])
            L = seq.shape[0]
            attention_mask = get_selfless_mask(sigma=sigma.unsqueeze(0), seq_len=L, device=device)
            hidden = self.model(
                X0_input_ids=seq.unsqueeze(0),
                attention_mask=attention_mask,
                token_types=token_types.unsqueeze(0),
                calculate_likelihood=True,
            ).last_hidden_state[0, -1]
            text_logits = self.lm_head(hidden.unsqueeze(0))
            if self.unified_head:
                text_logits = text_logits[..., :getattr(self.config, "image_offset", 200000)]
            next_token, _ = self._sample_from_logits(text_logits, temperature)
            next_token = next_token.item()
            seq[-1] = next_token
            generated_text_tokens += 1

            if eos_token_id is not None and next_token == eos_token_id:
                break

            if next_token != boi_token_id:
                continue

            image_masks = torch.full(
                (image_tokens_per_img,), self.config.mask_token_id, device=device, dtype=torch.long
            )
            eoi = torch.tensor([eoi_token_id], device=device, dtype=torch.long)
            seq = torch.cat([seq, image_masks, eoi])
            image_types = torch.full((image_tokens_per_img,), 1, device=device, dtype=torch.uint8)
            eoi_type = torch.tensor([2], device=device, dtype=torch.uint8)
            token_types = torch.cat([token_types, image_types, eoi_type])
            # EOI gets earlier sigma than image mask tokens, matching training:
            # image queries can condition on the known fixed image boundary.
            eoi_sigma = next_sigma_values(1)
            image_sigma = torch.full(
                (image_tokens_per_img,),
                float(eoi_sigma.item() + image_tokens_per_img + 1.0),
                device=device,
                dtype=sigma.dtype,
            )
            sigma = torch.cat([sigma, image_sigma, eoi_sigma])

            image_start = seq.shape[0] - image_tokens_per_img - 1
            image_end = seq.shape[0] - 1
            next_image_order = float(eoi_sigma.item() + 1.0)
            while seq[image_start:image_end].eq(self.config.mask_token_id).any():
                L = seq.shape[0]
                attention_mask = get_selfless_mask(sigma=sigma.unsqueeze(0), seq_len=L, device=device)
                hidden = self.model(
                    X0_input_ids=seq.unsqueeze(0),
                    attention_mask=attention_mask,
                    token_types=token_types.unsqueeze(0),
                    calculate_likelihood=True,
                ).last_hidden_state[0]
                valid_mask = seq[image_start:image_end].eq(self.config.mask_token_id)
                image_hidden = hidden[image_start:image_end]
                image_logits = self._image_logits_from_hidden(image_hidden)
                next_image_tokens, conf = self._sample_from_logits(image_logits, temperature)
                fill_local = self._select_fill_mask(conf, valid_mask, ratio, parallel_rate, decode_strategy)
                fill_positions = image_start + fill_local.nonzero(as_tuple=True)[0]
                seq[fill_positions] = next_image_tokens[fill_local]
                if fill_positions.numel() > 0:
                    new_sigma = torch.arange(
                        next_image_order,
                        next_image_order + fill_positions.numel(),
                        device=device,
                        dtype=sigma.dtype,
                    )
                    sigma[fill_positions] = new_sigma
                    next_image_order += float(fill_positions.numel())
                    image_tokens_filled += int(fill_positions.numel())
                image_fill_steps += 1

        return seq, token_types, image_tokens_filled, image_fill_steps

    @torch.no_grad()
    def generate(self, prompt_ids, gen_length, num_response=1, prompt_task='ar', block_size=4, temperature=1.0, ratio=None, parallel_rate=None, decode_strategy='confidence', **kwargs):
        if prompt_ids.dim() == 1:
            prompt_ids = prompt_ids.unsqueeze(0)
        base_prompts = prompt_ids.to(self.device)
        if base_prompts.shape[0] == 1:
            base_prompts = base_prompts.repeat(num_response, 1)
        elif base_prompts.shape[0] != num_response:
            raise ValueError("prompt_ids batch size must be 1 or equal to num_response")

        seqs = []
        type_seqs = []
        total_image_tokens = 0
        total_image_steps = 0
        for i in range(num_response):
            seq, token_types, image_tokens, image_steps = self._generate_one(
                prompt_ids=base_prompts[i],
                gen_length=gen_length,
                prompt_task=prompt_task,
                block_size=block_size,
                temperature=temperature,
                ratio=ratio,
                parallel_rate=parallel_rate,
                decode_strategy=decode_strategy,
            )
            seqs.append(seq)
            type_seqs.append(token_types)
            total_image_tokens += image_tokens
            total_image_steps += image_steps

        max_len = max(seq.shape[0] for seq in seqs)
        pad_id = getattr(self.config, "eos_token_id", None)
        if pad_id is None:
            pad_id = 0
        output = torch.full((num_response, max_len), pad_id, device=self.device, dtype=torch.long)
        raw_output = torch.full((num_response, max_len), pad_id, device=self.device, dtype=torch.long)
        output_token_types = torch.full((num_response, max_len), 3, device=self.device, dtype=torch.uint8)
        image_offset = getattr(self.config, "image_offset", 200000)
        for i, seq in enumerate(seqs):
            token_types = type_seqs[i]
            raw_output[i, :seq.shape[0]] = seq
            output_token_types[i, :token_types.shape[0]] = token_types
            display_seq = seq.clone()
            image_mask = token_types == 1
            display_seq[image_mask] = display_seq[image_mask] + image_offset
            output[i, :seq.shape[0]] = display_seq

        effective_parallel_rate = (
            (total_image_tokens / max(1, num_response)) / total_image_steps
            if total_image_steps > 0 else 0.0
        )
        return {
            'seq': output,
            'raw_seq': raw_output,
            'token_types': output_token_types,
            'parallel_rate': effective_parallel_rate,
        }
        
    @torch.no_grad()
    def speculative_generate(self, prompt_ids, gen_length, num_response=1, prompt_task='ar', block_size=4, temperature=1.0, ratio=None, parallel_rate=None):
        from utils.utils import get_selfless_mask
        
        # 1. 初始化
        if prompt_ids.dim() == 1:
            prompt_ids = prompt_ids.unsqueeze(0)
        prompt_ids = prompt_ids.repeat(num_response, 1)
        
        prompt_len = prompt_ids.shape[-1]
        prefix = prompt_ids.to(self.device)
        
        # 初始化全局 Sigma
        max_seq_len = prompt_len + gen_length + block_size
        sigma = torch.zeros((num_response, max_seq_len), dtype=torch.float32, device=self.device)
        
        # Context 的 Sigma 设置
        if prompt_task == 'ar':
            sigma[:, :prompt_len] = torch.arange(0, prompt_len, device=self.device)
        elif prompt_task == 'diffusion':
            sigma[:, :prompt_len] = torch.rand(num_response, prompt_len, device=self.device)
        else:
            raise ValueError(f"Invalid prompt task: {prompt_task}")

        global_step = 0 
        generated_tokens = 0
        end_token_id = getattr(self.config, 'eos_token_id', None)

        while prefix.shape[-1] < prompt_len + gen_length:
            curr_len = prefix.shape[-1]
            curr_block_size = min(block_size, prompt_len + gen_length - curr_len)
            if curr_block_size <= 0: break
            seq_len = curr_len + curr_block_size
            block_order = torch.arange(curr_len, seq_len, device=self.device, dtype=sigma.dtype)
            sigma[:, curr_len:seq_len] = block_order.unsqueeze(0)
            
            # ==============================================================
            # Phase 1: Draft
            # ==============================================================
            draft_seq = torch.full((num_response, seq_len), self.config.mask_token_id, device=self.device)
            draft_seq[:, :curr_len] = prefix
            
            draft_sigma = sigma.clone() 
            # 保持 float32 以确保精度
            draft_token_probs = torch.zeros((num_response, curr_block_size), dtype=torch.float32, device=self.device)
            draft_inner_order = float(curr_len)
            
            while draft_seq[:, curr_len:].eq(self.config.mask_token_id).any():
                attention_mask = get_selfless_mask(sigma=draft_sigma[:, :seq_len], seq_len=seq_len, device=self.device)
                
                logits = self(draft_seq, attention_mask=attention_mask, calculate_likelihood=True).logits
                
                if temperature < 1e-6:
                    probs = torch.softmax(logits, dim=-1)
                    next_token = logits.argmax(dim=-1)
                else:
                    probs = torch.softmax(logits / temperature, dim=-1)
                    next_token = torch.multinomial(probs.reshape(-1, probs.size(-1)), 1).view(num_response, -1)
                
                conf = probs.gather(-1, next_token.unsqueeze(-1)).squeeze(-1)
                valid_mask = draft_seq.eq(self.config.mask_token_id)
                masked_conf = conf.masked_fill(~valid_mask, -1.0)
                
                if parallel_rate is not None:
                    k_p = max(1, int(parallel_rate))
                    topk_values, topk_indices = torch.topk(masked_conf, k=k_p, dim=-1)
                    fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                    fill_mask.scatter_(1, topk_indices, topk_values > -0.5)
                elif ratio is not None:
                    fill_mask = (masked_conf >= ratio)
                    rows_with_no_fill = ~(fill_mask.any(dim=-1))
                    rows_still_have_mask = valid_mask.any(dim=-1)
                    rows_need_fallback = rows_with_no_fill & rows_still_have_mask
                    if rows_need_fallback.any():
                        fallback_cols = masked_conf[rows_need_fallback].argmax(dim=-1)
                        fill_mask[rows_need_fallback, fallback_cols] = True
                else:
                    fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                    fill_mask.scatter_(1, masked_conf.argmax(dim=-1, keepdim=True), True)
                
                rows, cols = fill_mask.nonzero(as_tuple=True)
                draft_seq[rows, cols] = next_token[rows, cols]
                
                block_cols = cols - curr_len
                valid_updates = (block_cols >= 0) & (block_cols < curr_block_size)
                if valid_updates.any():
                    r_ = rows[valid_updates]
                    c_ = cols[valid_updates] 
                    bc_ = block_cols[valid_updates]
                    # 【修复点】：显式转换 dtype，解决 BFloat16 -> Float32 赋值报错
                    draft_token_probs[r_, bc_] = conf[r_, c_].to(dtype=draft_token_probs.dtype)

                draft_sigma[rows, cols] = draft_inner_order
                draft_inner_order += 1.0
            
            draft_tokens = draft_seq[:, curr_len:]

            # ==============================================================
            # Phase 2: Verify
            # ==============================================================
            verify_sigma = sigma.clone()
            
            block_ar_sigmas = torch.arange(curr_len, seq_len, device=self.device, dtype=sigma.dtype)
            
            verify_sigma[:, curr_len:seq_len] = block_ar_sigmas.unsqueeze(0)
            
            verify_attention_mask = get_selfless_mask(sigma=verify_sigma[:, :seq_len], seq_len=seq_len, device=self.device)
            
            verify_outputs = self(draft_seq, attention_mask=verify_attention_mask, calculate_likelihood=True)
            verify_logits = verify_outputs.logits[:, curr_len:, :]
            
            if temperature < 1e-6:
                target_probs = torch.softmax(verify_logits, dim=-1)
            else:
                target_probs = torch.softmax(verify_logits / temperature, dim=-1)

            # ==============================================================
            # Phase 3: Accept / Reject
            # ==============================================================
            target_token_probs = target_probs.gather(-1, draft_tokens.unsqueeze(-1)).squeeze(-1)
            
            # 【优化点】：统一转换为 float32 进行除法运算，保证稳定性
            acc_ratios = target_token_probs.to(torch.float32) / (draft_token_probs + 1e-10)
            accept_mask = torch.rand_like(acc_ratios) < acc_ratios
            
            num_accepted = accept_mask.cumprod(dim=1).sum(dim=1).long()
            safe_n = num_accepted.min().item() 
            
            prefix = torch.cat([prefix, draft_tokens[:, :safe_n]], dim=1)
            
            accepted_sigmas = torch.arange(curr_len, curr_len + safe_n, device=self.device, dtype=sigma.dtype)
            sigma[:, curr_len : curr_len+safe_n] = accepted_sigmas.unsqueeze(0)
            
            global_step += safe_n
            generated_tokens += safe_n
            
            if safe_n < curr_block_size:
                resampled_token = torch.multinomial(target_probs[:, safe_n, :], 1)
                prefix = torch.cat([prefix, resampled_token], dim=1)
                
                sigma[:, curr_len+safe_n] = float(curr_len + safe_n)
                
                global_step += 1
                generated_tokens += 1
                
            if end_token_id is not None:
                new_part = prefix[:, curr_len:]
                if (new_part == end_token_id).any(dim=-1).all():
                    break
                    
        parallel_rate_metric = (generated_tokens / num_response) / (global_step + 1e-6) if global_step > 0 else 0.0
            
        return {
            'seq': prefix,
            'parallel_rate': parallel_rate_metric
        }
    
class Qwen3ForSequenceClassification(GenericForSequenceClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForTokenClassification(GenericForTokenClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForQuestionAnswering(GenericForQuestionAnswering, Qwen3PreTrainedModel):
    base_model_prefix = "transformer"  # For BC, where `transformer` was used instead of `model`


__all__ = [
    "Qwen3ForCausalLM",
    "Qwen3ForQuestionAnswering",
    "Qwen3PreTrainedModel",
    "Qwen3Model",
    "Qwen3ForSequenceClassification",
    "Qwen3ForTokenClassification",
]
