#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3/modular_qwen3.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen team, Alibaba Group and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from typing import Callable, Optional, Union

import torch
from torch import nn
from torch.nn import functional as F

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import (
    GenericForQuestionAnswering,
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from transformers.modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.models.qwen3.configuration_qwen3 import Qwen3Config
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple
from transformers.utils.deprecation import deprecate_kwarg
from transformers.utils.generic import maybe_autocast, merge_with_config_defaults
from torch.nn.attention.flex_attention import flex_attention, BlockMask, create_block_mask, and_masks
from flash_attn.ops.triton.layer_norm import rms_norm_fn as flash_rms_norm
try:
    from liger_kernel.ops.swiglu import LigerSiLUMulFunction  # noqa: F401
    liger_kernel_is_available = True
except ImportError:
    liger_kernel_is_available = False
    

@use_kernel_forward_from_hub("RMSNorm")
class Qwen3RMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        Qwen3RMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        return flash_rms_norm(
            hidden_states, weight=self.weight, bias=None, eps=self.variance_epsilon)
        '''
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * \
            torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)
        '''

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class Qwen3MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(
            self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        if liger_kernel_is_available:
            return self.down_proj(LigerSiLUMulFunction.apply(self.gate_proj(x), self.up_proj(x)))
        else:
            down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
            return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(X0_q, XT_q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    X0_q_embed = (X0_q * cos) + (rotate_half(X0_q) * sin)
    XT_q_embed = (XT_q * cos) + (rotate_half(XT_q) * sin) if XT_q is not None else None
    k_embed = (k * cos) + (rotate_half(k) * sin)
    
    return X0_q_embed, XT_q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


@torch.compile(fullgraph=True, mode="max-autotune-no-cudagraphs")
def compiled_flex_attention(query, key, value, attention_mask, scaling, enable_gqa):
    """编译优化的 flex_attention 包装函数"""
    return flex_attention(
        query=query,
        key=key,
        value=value,
        score_mod=None,
        block_mask=attention_mask,
        scale=scaling,
        enable_gqa=enable_gqa,
        return_lse=False,
    )

@torch.compile(
    fullgraph=True,
    mode="default",
    dynamic=True
)
def uncompiled_flex_attention(query, key, value, attention_mask, scaling, enable_gqa):
    """不适用编译优化的 flex_attention 包装函数"""
    return flex_attention(
        query=query,
        key=key,
        value=value,
        score_mod=None,
        block_mask=attention_mask,
        scale=scaling,
        enable_gqa=enable_gqa,
        return_lse=False,
    )
    
# @torch.compile()
def eager_diffusion_attention(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        if attention_mask.dim() == 3:
            attention_mask = attention_mask.unsqueeze(1)
        diffusion_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + diffusion_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights

    
class Qwen3Attention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: Qwen3Config, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        self.q_norm = Qwen3RMSNorm(self.head_dim, eps=config.rms_norm_eps)  # unlike olmo, only on the head dim!
        self.k_norm = Qwen3RMSNorm(self.head_dim, eps=config.rms_norm_eps)  # thus post q_norm does not need reshape

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: BlockMask,
        past_key_values: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        input_shape = X0_hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)
            
        XT_query_states = self.q_norm(self.q_proj(XT_hidden_states).view(hidden_shape)).transpose(1, 2) if self.training else None
        
        X0_query_states = self.q_norm(self.q_proj(X0_hidden_states).view(hidden_shape)).transpose(1, 2)
        X0_key_states = self.k_norm(self.k_proj(X0_hidden_states).view(hidden_shape)).transpose(1, 2)
        X0_value_states = self.v_proj(X0_hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        X0_query_states, XT_query_states, X0_key_states,  = apply_rotary_pos_emb(X0_query_states, XT_query_states, X0_key_states, cos, sin)

        if past_key_values is not None:
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            X0_key_states, X0_value_states = past_key_values.update(X0_key_states, X0_value_states, self.layer_idx, cache_kwargs)
        
        # 检查是否需要 GQA (Grouped Query Attention)
        enable_gqa = self.config.num_attention_heads != self.config.num_key_value_heads
        
        if self.config.use_flex_attention == False or self.training == False:
            X0_attn_output = uncompiled_flex_attention(
                query=X0_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            )
            XT_attn_output = uncompiled_flex_attention(
                query=XT_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            ) if self.training else None
            attn_weights = None
        else:
            # 调用 flex_attention
            X0_attn_output = compiled_flex_attention(
                query=X0_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            )
            XT_attn_output = compiled_flex_attention(
                query=XT_query_states,
                key=X0_key_states,
                value=X0_value_states,
                attention_mask=attention_mask,  # 直接传入 BlockMask
                scaling=self.scaling,  # 使用预定义的缩放因子
                enable_gqa=enable_gqa,  # 如果 kv heads 少于 q heads，需要启用
            ) if self.training else None
            attn_weights = None
        
        # attn_output 形状: (batch, heads, seq_len, head_dim)
        # 需要转换回 (batch, seq_len, hidden_size)
        X0_attn_output = X0_attn_output.transpose(1, 2).reshape(*input_shape, -1).contiguous()
        XT_attn_output = XT_attn_output.transpose(1, 2).reshape(*input_shape, -1).contiguous() if self.training else None
        X0_attn_output = self.o_proj(X0_attn_output)
        XT_attn_output = self.o_proj(XT_attn_output) if self.training else None
        
        return X0_attn_output, XT_attn_output, attn_weights


class Qwen3DecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: Qwen3Config, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = Qwen3Attention(config=config, layer_idx=layer_idx)

        self.mlp = Qwen3MLP(config)
        self.input_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.attention_type = config.layer_types[layer_idx]

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor,
        attention_mask: BlockMask,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        X0_residual = X0_hidden_states
        XT_residual = XT_hidden_states if self.training else None
        X0_hidden_states = self.input_layernorm(X0_hidden_states)
        XT_hidden_states = self.input_layernorm(XT_hidden_states) if self.training else None
        # Self Attention
        X0_hidden_states, XT_hidden_states, _ = self.self_attn(
            X0_hidden_states=X0_hidden_states,
            XT_hidden_states=XT_hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        X0_hidden_states = X0_residual + X0_hidden_states
        XT_hidden_states = XT_residual + XT_hidden_states if self.training else None

        # Fully Connected
        X0_residual = X0_hidden_states
        XT_residual = XT_hidden_states if self.training else None
        X0_hidden_states = self.post_attention_layernorm(X0_hidden_states)
        XT_hidden_states = self.post_attention_layernorm(XT_hidden_states) if self.training else None
        X0_hidden_states = self.mlp(X0_hidden_states)
        XT_hidden_states = self.mlp(XT_hidden_states) if self.training else None
        X0_hidden_states = X0_residual + X0_hidden_states
        XT_hidden_states = XT_residual + XT_hidden_states if self.training else None
        return X0_hidden_states, XT_hidden_states


@auto_docstring
class Qwen3PreTrainedModel(PreTrainedModel):
    config: Qwen3Config
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["Qwen3DecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": Qwen3DecoderLayer,
        "attentions": Qwen3Attention,
    }


class Qwen3RotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: Qwen3Config, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: Qwen3Config | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class Qwen3Model(Qwen3PreTrainedModel):
    def __init__(self, config: Qwen3Config):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.image_vocab_size = getattr(config, "image_vocab_size", 16384)
        self.image_embed_tokens = nn.Embedding(self.image_vocab_size, config.hidden_size)
        self.layers = nn.ModuleList(
            [Qwen3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = Qwen3RotaryEmbedding(config=config)
        self.gradient_checkpointing = False
        self.XT_input_ids = None

        # Initialize weights and apply final processing
        self.post_init()

    # @check_model_inputs
    @auto_docstring
    def forward(
        self,
        X0_input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[BlockMask] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        X0_inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        r"""
        Args:
            time_sample (`torch.Tensor` of shape `(batch_size, sequence_length + 1)`, *optional*):
                Time sampling tensor for diffusion-causal attention. Each element represents the diffusion time step
                for the corresponding token. Tokens with larger time values cannot attend to tokens with smaller time
                values. The first element should be 1.1 to ensure all tokens can attend to the first position.
        """
        if (X0_input_ids is None) ^ (X0_inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")
        if attention_mask is None:
            raise ValueError("attention_mask must be provided for diffusion-causal attention.")

        if X0_inputs_embeds is None:
            image_offset = getattr(self.config, "image_offset", 200000)
            is_image = X0_input_ids >= image_offset
            is_text = ~is_image

            X0_inputs_embeds = torch.zeros(
                (*X0_input_ids.shape, self.config.hidden_size),
                dtype=self.embed_tokens.weight.dtype,
                device=X0_input_ids.device,
            )
            # Text tokens -> text embedding
            X0_inputs_embeds[is_text] = self.embed_tokens(X0_input_ids[is_text])
            # Image tokens -> image embedding (undo offset)
            if is_image.any():
                img_indices = X0_input_ids[is_image] - image_offset
                X0_inputs_embeds[is_image] = self.image_embed_tokens(img_indices)

        if self.training:
            if self.XT_input_ids is None or self.XT_input_ids.shape[-1] != X0_input_ids.shape[-1]:
                self.XT_input_ids = torch.full_like(X0_input_ids, self.config.mask_token_id)
            # XT stream: mask tokens use text embedding (XT always gets [MASK] embeddings)
            XT_inputs_embeds = self.embed_tokens(self.XT_input_ids)
        else:
            self.XT_input_ids = None
            XT_inputs_embeds = None

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + X0_inputs_embeds.shape[1], device=X0_inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        X0_hidden_states = X0_inputs_embeds
        XT_hidden_states = XT_inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(X0_hidden_states, position_ids)
        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            X0_hidden_states, XT_hidden_states = decoder_layer(
                X0_hidden_states,
                XT_hidden_states,
                attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )

        if not self.training:
            X0_hidden_states = self.norm(X0_hidden_states)
            return BaseModelOutputWithPast(
                last_hidden_state=X0_hidden_states,
                past_key_values=past_key_values if use_cache else None,
            )
        else:
            XT_hidden_states = self.norm(XT_hidden_states)
            return BaseModelOutputWithPast(
                last_hidden_state=XT_hidden_states,
                past_key_values=past_key_values if use_cache else None,
            )


@auto_docstring
class Qwen3ForCausalLM(Qwen3PreTrainedModel, GenerationMixin):
    _tied_weights_keys = {}  # Don't tie — multimodal needs separate spaces
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = Qwen3Model(config)
        self.vocab_size = config.vocab_size
        self.image_vocab_size = getattr(config, "image_vocab_size", 16384)
        self.unified_head = getattr(config, "unified_head", False)
        self.lambda_image = getattr(config, "lambda_image", 0.5)

        if self.unified_head:
            # Single unified head: text vocab (already includes special tokens) + image vocab
            image_offset = getattr(config, "image_offset", len(config) if hasattr(config, '__len__') else 200000)
            total_vocab = image_offset + self.image_vocab_size
            self.lm_head = nn.Linear(config.hidden_size, total_vocab, bias=False)
            self.image_lm_head = None
        else:
            self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
            self.image_lm_head = nn.Linear(config.hidden_size, self.image_vocab_size, bias=False)

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        X0_input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[BlockMask] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.
        
        time_sample (`torch.Tensor` of shape `(batch_size, sequence_length + 1)`, *optional*):
                Time sampling tensor for diffusion-causal attention. Each element represents the diffusion time step
                for the corresponding token. Tokens with larger time values cannot attend to tokens with smaller time
                values. The first element should be 1.1 to ensure all tokens can attend to the first position.
        Example:

        ```python
        >>> from transformers import AutoTokenizer, Qwen3ForCausalLM

        >>> model = Qwen3ForCausalLM.from_pretrained("Qwen/Qwen3-8B")
        >>> tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-8B")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""
        outputs: BaseModelOutputWithPast = self.model(
            X0_input_ids=X0_input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        token_types = kwargs.get("token_types", None)

        loss = None
        if labels is not None:
            if token_types is not None:
                image_offset = getattr(self.config, "image_offset", 200000)
                text_mask = (token_types == 0) | (token_types == 2)
                image_mask = token_types == 1

                flat_hidden = hidden_states.view(-1, hidden_states.size(-1))
                flat_labels = labels.view(-1)

                text_flat_mask = text_mask.view(-1)
                image_flat_mask = image_mask.view(-1)

                if self.unified_head:
                    # Single head: one CE loss over all positions
                    loss = F.cross_entropy(
                        self.lm_head(flat_hidden), flat_labels, ignore_index=-100
                    )
                    # Post-hoc per-modality metrics
                    text_loss = torch.tensor(0.0, device=flat_hidden.device)
                    image_loss = torch.tensor(0.0, device=flat_hidden.device)
                    with torch.no_grad():
                        if text_flat_mask.any():
                            text_logits = self.lm_head(flat_hidden[text_flat_mask])
                            text_loss = F.cross_entropy(
                                text_logits, flat_labels[text_flat_mask], ignore_index=-100
                            )
                        if image_flat_mask.any():
                            image_logits = self.lm_head(flat_hidden[image_flat_mask])
                            image_loss = F.cross_entropy(
                                image_logits, flat_labels[image_flat_mask], ignore_index=-100
                            )
                else:
                    # Dual head: separate heads for text and image
                    text_loss = 0.0
                    if text_flat_mask.any():
                        text_logits = self.lm_head(flat_hidden[text_flat_mask])
                        text_loss = F.cross_entropy(
                            text_logits, flat_labels[text_flat_mask], ignore_index=-100
                        )

                    image_loss = 0.0
                    if image_flat_mask.any():
                        image_logits = self.image_lm_head(flat_hidden[image_flat_mask])
                        image_labels = flat_labels[image_flat_mask] - image_offset
                        image_loss = F.cross_entropy(
                            image_logits, image_labels, ignore_index=-100
                        )

                    loss = text_loss + self.lambda_image * image_loss
            else:
                loss = self.loss_function(
                    logits.view(-1, logits.size(-1)), labels.view(-1), ignore_index=-100
                )

        output = CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )
        # Attach per-modality losses for logging
        if token_types is not None and loss is not None:
            output.per_modality_loss = {
                "text_loss": text_loss.detach() if isinstance(text_loss, torch.Tensor) else torch.tensor(text_loss or 0.0, device=hidden_states.device),
                "image_loss": image_loss.detach() if isinstance(image_loss, torch.Tensor) else torch.tensor(image_loss or 0.0, device=hidden_states.device),
            }
        return output
        
    @torch.compile(mode="max-autotune-no-cudagraphs")
    def loss_function(self, logits, labels, ignore_index, reduction='mean'):
        return F.cross_entropy(logits.view(-1, logits.size(-1)), labels.view(-1), ignore_index=ignore_index, reduction=reduction)
    
    # def forward_process(
    #     self,
    #     X0_input_ids, 
    #     labels,
    #     attention_mask,
    #     return_logits=False,
    # ):
    #     logits = self.forward(X0_input_ids=X0_input_ids, attention_mask=attention_mask).logits  # shape: [B, L, V]

    #     loss = self.loss_function(logits.view(-1, logits.size(-1)), labels.view(-1), ignore_index=-100)
    
    #     if return_logits:
    #         return loss, logits.detach()
    #     else:
    #         return loss
        
    # def forward_process_inference(
    #     self,
    #     input_ids, 
    #     labels,
    #     p_mask,
    #     masked_indices,
    #     attention_mask=None,
    #     return_logits=False,
    # ):
    #     logits = self.forward(X0_input_ids=input_ids, attention_mask=attention_mask).logits  # shape: [B, L, V]
        
    #     loss = self.loss_function(
    #         logits[masked_indices],
    #         labels[masked_indices],
    #         ignore_index=-100,
    #         reduction='none',
    #     )
    #     loss = loss / p_mask[masked_indices]
    #     loss = loss.sum() / (labels.shape[0] * labels.shape[1])
        
    #     if return_logits:
    #         return loss, logits.detach()
    #     else:
    #         return loss 
        
        
    # def forward_process_sft(
    #     self,
    #     X0_input_ids,
    #     labels,
    #     attention_mask,
    #     return_logits=False,
    # ):
    #     logits = self.forward(X0_input_ids=X0_input_ids, attention_mask=attention_mask).logits  # shape: [B, L, V]
    #     # 使用 reduction='none' 获取每个token的loss，然后对每个样本求平均，再对batch求平均
    #     # 这样每个样本的贡献是相等的，而不是每个token的贡献相等
    #     loss_per_token =  self.loss_function(
    #         logits.view(-1, logits.size(-1)), 
    #         labels.view(-1), 
    #         ignore_index=-100,
    #         reduction='none'
    #     )  # shape: [B*L]
    #     loss_per_token = loss_per_token.view(labels.shape)  # shape: [B, L]
    #     # 对每个样本求平均（忽略-100的token）
    #     valid_mask = (labels != -100).float()  # shape: [B, L]
    #     loss_per_sample = (loss_per_token * valid_mask).sum(dim=1) / valid_mask.sum(dim=1).clamp(min=1)  # shape: [B]
    #     # 对所有样本求平均
    #     loss = loss_per_sample.mean()
        
    #     if return_logits:
    #         return loss, logits.detach()
    #     else:
    #         return loss
        
    @torch.no_grad()
    def generate(self, prompt_ids, gen_length, num_response=1, prompt_task='ar', block_size=4, temperature=1.0, ratio=None, parallel_rate=None, decode_strategy='confidence'):
        from utils.utils import get_selfless_mask
        # 确保 prompt_ids 是 [1, L] 并复制为 [batch, L]
        if prompt_ids.dim() == 1:
            prompt_ids = prompt_ids.unsqueeze(0)
        prompt_ids = prompt_ids.repeat(num_response, 1)
        
        prompt_len = prompt_ids.shape[-1]
        prefix = prompt_ids.to(self.device)
        # sigma 需要足够长以容纳 prompt + gen_length + block_size
        max_seq_len = prompt_len + gen_length + block_size
        sigma = torch.zeros((num_response, max_seq_len), dtype=torch.float32, device=self.device)
        
        # init sigma for prompt tokens
        if prompt_task == 'ar':
            sigma[:, :prompt_len] = prompt_len + 1 - torch.arange(0, prompt_len, device=self.device)
        elif prompt_task == 'diffusion':
            sigma[:, :prompt_len] = torch.rand(num_response, prompt_len, device=self.device) + 1.0
        else:
            raise ValueError(f"Invalid prompt task: {prompt_task}")
        step = 0
        generated_tokens = 0

        while (prefix.shape[-1] < prompt_len + gen_length):
            # seq: [batch, seq_len + block_size]
            seq_len = prefix.shape[-1] + block_size
            seq = torch.full((num_response, seq_len), self.config.mask_token_id, device=self.device)
            # 将 prefix 的内容复制到 seq 的前面部分
            seq[:, :prefix.shape[-1]] = prefix
            attention_mask = get_selfless_mask(v_sample=sigma[:, :seq_len], seq_len=seq_len, device=self.device)
                        
            # 只要 batch 中任意一个样本在当前 block 还有 mask，就继续循环
            while seq.eq(self.config.mask_token_id).any():
                logits = self(seq, attention_mask=attention_mask).logits # [batch, L, V]
                
                if temperature < 1e-6:
                    probs = torch.softmax(logits, dim=-1)
                    next_token = logits.argmax(dim=-1)
                else:
                    probs = torch.softmax(logits / temperature, dim=-1)
                    # 展平 batch 维度进行采样，然后再恢复形状 [batch, L]
                    next_token = torch.multinomial(probs.reshape(-1, probs.size(-1)), 1).view(num_response, -1)
                
                # 计算置信度
                conf = probs.gather(-1, next_token.unsqueeze(-1)).squeeze(-1)  # [batch, L]
                
                # 构建掩码 [batch, L]
                valid_mask = seq.eq(self.config.mask_token_id)
                masked_conf = conf.masked_fill(~valid_mask, -1.0)
                
                # 决策填充位置
                if decode_strategy == 'random':
                    fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                    rows_still_have_mask = valid_mask.any(dim=-1)  # [batch]
                    if rows_still_have_mask.any():
                        rows_idx = rows_still_have_mask.nonzero(as_tuple=True)[0]  # 需采样的 batch 行
                        # 在各行的有效 mask 位置上均匀采样parallel_rate个列索引
                        sampled_cols = torch.multinomial(valid_mask[rows_idx].float(), num_samples=1 if parallel_rate is None else max(1, int(parallel_rate)), replacement=False)
                        fill_mask[rows_idx, sampled_cols] = True
                elif decode_strategy == 'confidence':
                    if parallel_rate is not None:
                        k = int(parallel_rate)
                        k = max(1, k)
                        # 选取置信度最高的 k 个位置
                        topk_values, topk_indices = torch.topk(masked_conf, k=k, dim=-1)
                        
                        fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                        # 过滤掉非mask位置（值为-1.0的位置），确保只填充有效的mask token
                        fill_mask.scatter_(1, topk_indices, topk_values > -0.5)
                    elif ratio is not None:
                        fill_mask = (masked_conf >= ratio)
                        # Fallback: 检查哪些 batch 样本没有选中任何位置，强制选最好的一个
                        # 但需要排除已经生成完的样本（没有mask token的样本）
                        rows_with_no_fill = ~(fill_mask.any(dim=-1))
                        # 只对还有mask token的样本进行fallback
                        rows_still_have_mask = valid_mask.any(dim=-1)  # [batch]
                        rows_need_fallback = rows_with_no_fill & rows_still_have_mask
                        if rows_need_fallback.any():
                            fallback_cols = masked_conf[rows_need_fallback].argmax(dim=-1)
                            fill_mask[rows_need_fallback, fallback_cols] = True
                    else:
                        # 每个 batch 样本选一个置信度最高的
                        fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                        fill_mask.scatter_(1, masked_conf.argmax(dim=-1, keepdim=True), True)
                
                # 批量更新：获取 batch 索引(rows)和位置索引(cols)
                rows, cols = fill_mask.nonzero(as_tuple=True)
                seq[rows, cols] = next_token[rows, cols]
                # 更新sigma
                sigma[rows, cols] = 0.1 + 0.8 * (1.0 - step / (gen_length + 1.0))
                generated_tokens += len(rows)
                step += 1
            prefix = seq
            # 如果batch中所有样本都包含了<|im_end|> token，则停止生成
            # 注意：只检查生成的部分（prompt_len之后），不检查prompt部分
            # end_token_id = getattr(self.config, 'im_end_token_id', None)
            end_token_id = getattr(self.config, 'eos_token_id', None)
            if end_token_id is not None:
                # 只检查生成的部分（prompt_len之后）是否包含 end_token_id
                generated_part = seq[:, prompt_len:]  # [batch, generated_len]
                has_end = (generated_part == end_token_id).any(dim=-1)  # [batch]
                if has_end.all():
                    seq = seq.masked_fill(seq.eq(self.config.mask_token_id), end_token_id)
                    break
        
        if step > 0:
            parallel_rate = (generated_tokens / num_response) / step
        else:
            parallel_rate = 0.0
        out_put = {
            'seq': seq,
            'parallel_rate': parallel_rate,
        }
        
        return out_put
        
    @torch.no_grad()
    def speculative_generate(self, prompt_ids, gen_length, num_response=1, prompt_task='ar', block_size=4, temperature=1.0, ratio=None, parallel_rate=None):
        from utils.utils import get_selfless_mask
        
        # 1. 初始化
        if prompt_ids.dim() == 1:
            prompt_ids = prompt_ids.unsqueeze(0)
        prompt_ids = prompt_ids.repeat(num_response, 1)
        
        prompt_len = prompt_ids.shape[-1]
        prefix = prompt_ids.to(self.device)
        
        # 初始化全局 Sigma
        max_seq_len = prompt_len + gen_length + block_size
        sigma = torch.zeros((num_response, max_seq_len), dtype=torch.float32, device=self.device)
        
        # Context 的 Sigma 设置
        if prompt_task == 'ar':
            sigma[:, :prompt_len] = prompt_len + 1 - torch.arange(0, prompt_len, device=self.device)
        elif prompt_task == 'diffusion':
            sigma[:, :prompt_len] = torch.rand(num_response, prompt_len, device=self.device) + 1.0
        else:
            raise ValueError(f"Invalid prompt task: {prompt_task}")

        global_step = 0 
        generated_tokens = 0
        end_token_id = getattr(self.config, 'eos_token_id', None)

        while prefix.shape[-1] < prompt_len + gen_length:
            curr_len = prefix.shape[-1]
            curr_block_size = min(block_size, prompt_len + gen_length - curr_len)
            if curr_block_size <= 0: break
            seq_len = curr_len + curr_block_size
            
            # ==============================================================
            # Phase 1: Draft
            # ==============================================================
            draft_seq = torch.full((num_response, seq_len), self.config.mask_token_id, device=self.device)
            draft_seq[:, :curr_len] = prefix
            
            draft_sigma = sigma.clone() 
            # 保持 float32 以确保精度
            draft_token_probs = torch.zeros((num_response, curr_block_size), dtype=torch.float32, device=self.device)
            draft_inner_step = global_step
            
            while draft_seq[:, curr_len:].eq(self.config.mask_token_id).any():
                attention_mask = get_selfless_mask(v_sample=draft_sigma[:, :seq_len], seq_len=seq_len, device=self.device)
                
                logits = self(draft_seq, attention_mask=attention_mask).logits
                
                if temperature < 1e-6:
                    probs = torch.softmax(logits, dim=-1)
                    next_token = logits.argmax(dim=-1)
                else:
                    probs = torch.softmax(logits / temperature, dim=-1)
                    next_token = torch.multinomial(probs.reshape(-1, probs.size(-1)), 1).view(num_response, -1)
                
                conf = probs.gather(-1, next_token.unsqueeze(-1)).squeeze(-1)
                valid_mask = draft_seq.eq(self.config.mask_token_id)
                masked_conf = conf.masked_fill(~valid_mask, -1.0)
                
                if parallel_rate is not None:
                    k_p = max(1, int(parallel_rate))
                    topk_values, topk_indices = torch.topk(masked_conf, k=k_p, dim=-1)
                    fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                    fill_mask.scatter_(1, topk_indices, topk_values > -0.5)
                elif ratio is not None:
                    fill_mask = (masked_conf >= ratio)
                    rows_with_no_fill = ~(fill_mask.any(dim=-1))
                    rows_still_have_mask = valid_mask.any(dim=-1)
                    rows_need_fallback = rows_with_no_fill & rows_still_have_mask
                    if rows_need_fallback.any():
                        fallback_cols = masked_conf[rows_need_fallback].argmax(dim=-1)
                        fill_mask[rows_need_fallback, fallback_cols] = True
                else:
                    fill_mask = torch.zeros_like(masked_conf, dtype=torch.bool)
                    fill_mask.scatter_(1, masked_conf.argmax(dim=-1, keepdim=True), True)
                
                rows, cols = fill_mask.nonzero(as_tuple=True)
                draft_seq[rows, cols] = next_token[rows, cols]
                
                block_cols = cols - curr_len
                valid_updates = (block_cols >= 0) & (block_cols < curr_block_size)
                if valid_updates.any():
                    r_ = rows[valid_updates]
                    c_ = cols[valid_updates] 
                    bc_ = block_cols[valid_updates]
                    # 【修复点】：显式转换 dtype，解决 BFloat16 -> Float32 赋值报错
                    draft_token_probs[r_, bc_] = conf[r_, c_].to(dtype=draft_token_probs.dtype)

                draft_sigma[rows, cols] = 0.1 + 0.8 * (1.0 - draft_inner_step / (gen_length + 1.0))
                draft_inner_step += 1
            
            draft_tokens = draft_seq[:, curr_len:]

            # ==============================================================
            # Phase 2: Verify
            # ==============================================================
            verify_sigma = sigma.clone()
            
            block_steps = torch.arange(curr_block_size, device=self.device) + global_step
            block_ar_sigmas = 0.1 + 0.8 * (1.0 - block_steps / (gen_length + 1.0))
            
            verify_sigma[:, curr_len:seq_len] = block_ar_sigmas.unsqueeze(0)
            
            verify_attention_mask = get_selfless_mask(v_sample=verify_sigma[:, :seq_len], seq_len=seq_len, device=self.device)
            
            verify_outputs = self(draft_seq, attention_mask=verify_attention_mask)
            verify_logits = verify_outputs.logits[:, curr_len:, :]
            
            if temperature < 1e-6:
                target_probs = torch.softmax(verify_logits, dim=-1)
            else:
                target_probs = torch.softmax(verify_logits / temperature, dim=-1)

            # ==============================================================
            # Phase 3: Accept / Reject
            # ==============================================================
            target_token_probs = target_probs.gather(-1, draft_tokens.unsqueeze(-1)).squeeze(-1)
            
            # 【优化点】：统一转换为 float32 进行除法运算，保证稳定性
            acc_ratios = target_token_probs.to(torch.float32) / (draft_token_probs + 1e-10)
            accept_mask = torch.rand_like(acc_ratios) < acc_ratios
            
            num_accepted = accept_mask.cumprod(dim=1).sum(dim=1).long()
            safe_n = num_accepted.min().item() 
            
            prefix = torch.cat([prefix, draft_tokens[:, :safe_n]], dim=1)
            
            accepted_steps = torch.arange(safe_n, device=self.device) + global_step
            accepted_sigmas = 0.1 + 0.8 * (1.0 - accepted_steps / (gen_length + 1.0))
            sigma[:, curr_len : curr_len+safe_n] = accepted_sigmas.unsqueeze(0)
            
            global_step += safe_n
            generated_tokens += safe_n
            
            if safe_n < curr_block_size:
                resampled_token = torch.multinomial(target_probs[:, safe_n, :], 1)
                prefix = torch.cat([prefix, resampled_token], dim=1)
                
                new_sigma = 0.1 + 0.8 * (1.0 - global_step / (gen_length + 1.0))
                sigma[:, curr_len+safe_n] = new_sigma
                
                global_step += 1
                generated_tokens += 1
                
            if end_token_id is not None:
                new_part = prefix[:, curr_len:]
                if (new_part == end_token_id).any(dim=-1).all():
                    break
                    
        parallel_rate_metric = (generated_tokens / num_response) / (global_step + 1e-6) if global_step > 0 else 0.0
            
        return {
            'seq': prefix,
            'parallel_rate': parallel_rate_metric
        }
    
class Qwen3ForSequenceClassification(GenericForSequenceClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForTokenClassification(GenericForTokenClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForQuestionAnswering(GenericForQuestionAnswering, Qwen3PreTrainedModel):
    base_model_prefix = "transformer"  # For BC, where `transformer` was used instead of `model`


__all__ = [
    "Qwen3ForCausalLM",
    "Qwen3ForQuestionAnswering",
    "Qwen3PreTrainedModel",
    "Qwen3Model",
    "Qwen3ForSequenceClassification",
    "Qwen3ForTokenClassification",
]
