#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3/modular_qwen3.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen team, Alibaba Group and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
import importlib.machinery
import os
import sys
import types
from typing import Optional, Union

import torch
try:
    import torch_npu
except ImportError:  # CPU-only contract tests do not have the Ascend runtime.
    os.environ.setdefault("DS_ACCELERATOR", "cpu")
    torch_npu = types.ModuleType("torch_npu")
    torch_npu.__spec__ = importlib.machinery.ModuleSpec(
        "torch_npu", loader=None
    )
    sys.modules["torch_npu"] = torch_npu
from torch import nn
from torch.nn import functional as F
from torch.nn.attention.flex_attention import (
    BlockMask,
    flex_attention,
)
from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import (
    GenericForQuestionAnswering,
    GenericForSequenceClassification,
    GenericForTokenClassification,
    GradientCheckpointingLayer,
)
from transformers.modeling_outputs import (
    BaseModelOutputWithPast,
    CausalLMOutputWithPast,
)
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import PreTrainedModel
from transformers.models.qwen3.configuration_qwen3 import Qwen3Config
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, can_return_tuple
from transformers.utils.deprecation import deprecate_kwarg

from .image_flow_loss import FlowLoss
from .image_backbone import (
    CANONICAL_IMAGE_LATENT_DIM,
    CANONICAL_IMAGE_TOKENS,
    validate_model_image_layout,
)
from .image_position_utils import (
    build_row_col_position_ids,
)
from .modeling_selfless_generation import (
    SelflessGenerationMixin,
    SelflessStaticCache,
)


LEGACY_FLOW_CONDITION_CONTRACT = "backbone_xt_shared_query_content"
X0_CONTENT_FLOW_CONDITION_CONTRACT = (
    "backbone_xt_query_backbone_x0_content"
)
_FLOW_CONDITION_CONTRACTS = {
    LEGACY_FLOW_CONDITION_CONTRACT,
    X0_CONTENT_FLOW_CONDITION_CONTRACT,
}


class X0ContentFlowLoss(FlowLoss):
    """Contextual flow loss with an explicit backbone-X0 content condition.

    Historical A/B checkpoints omit ``flow_condition_contract`` and retain
    ``FlowLoss`` itself, including its query-condition fallback.  New A/B
    checkpoints use this parameter-free subclass so their query AdaLN receives
    backbone XT hidden states while content AdaLN receives backbone X0 hidden
    states.  Keeping the legacy class and call path untouched is important for
    bitwise-compatible loading of existing weights.
    """

    _CONTEXT_KEY = "_x0_content_training_context_conditions"

    def _training_context(
        self, target, sigma, image_positions, context_latents=None,
        context_mask=None, content_attention_mask=None,
    ):
        content_batch = target.shape[0] if context_latents is None else context_latents.shape[0]
        repeats, remainder = divmod(target.shape[0], content_batch)
        if remainder or repeats < 1:
            raise ValueError("query batch must be an integer multiple of content batch")
        shared = repeats > 1
        context = super()._training_context(
            context_latents if shared else target,
            sigma[:content_batch] if shared and sigma is not None else sigma,
            image_positions[:content_batch] if shared and image_positions is not None else image_positions,
            context_latents=context_latents,
            context_mask=context_mask[:content_batch] if shared and context_mask is not None else context_mask,
            content_attention_mask=(content_attention_mask[:content_batch]
                                    if shared and content_attention_mask is not None
                                    else content_attention_mask),
        )
        if shared:
            context["query_positions"] = (
                image_positions if image_positions is not None
                else context["context_positions"].repeat(repeats, 1)
            )
            context["query_batch_repeats"] = repeats
        context_conditions = self.__dict__.get(self._CONTEXT_KEY)
        if context_conditions is None:
            raise RuntimeError(
                "X0-content flow training requires an explicit backbone-X0 "
                "content condition"
            )
        expected = context["context_latents"].shape[:2]
        if tuple(context_conditions.shape[:2]) != tuple(expected):
            raise ValueError(
                "backbone-X0 content conditions must align with flow content: "
                f"{tuple(context_conditions.shape[:2])} != {tuple(expected)}"
            )
        context["context_conditions"] = context_conditions
        return context

    def forward(
        self,
        target,
        z,
        mask=None,
        sigma=None,
        image_positions=None,
        context_latents=None,
        context_mask=None,
        content_attention_mask=None,
        context_conditions=None,
        record_stats: bool = True,
        training_state=None,
    ):
        if context_conditions is None:
            raise ValueError(
                "X0-content flow training requires backbone-X0 "
                "context_conditions"
            )
        if self._CONTEXT_KEY in self.__dict__:
            raise RuntimeError("X0-content flow loss is not reentrant")
        self.__dict__[self._CONTEXT_KEY] = context_conditions
        try:
            return super().forward(
                target=target,
                z=z,
                mask=mask,
                sigma=sigma,
                image_positions=image_positions,
                context_latents=context_latents,
                context_mask=context_mask,
                content_attention_mask=content_attention_mask,
                record_stats=record_stats,
                training_state=training_state,
            )
        finally:
            self.__dict__.pop(self._CONTEXT_KEY, None)

def auto_docstring(obj=None, **_kwargs):
    def decorator(target):
        return target

    if obj is None:
        return decorator
    return decorator(obj)


def _normal_init_fp32_(tensor: torch.Tensor, mean: float = 0.0, std: float = 1.0):
    if tensor.is_meta:
        return
    with torch.no_grad():
        value = torch.empty(tensor.shape, device=tensor.device, dtype=torch.float32)
        nn.init.normal_(value, mean=mean, std=std)
        tensor.copy_(value.to(dtype=tensor.dtype))


class ImageTokenEmbedder(nn.Module):
    def __init__(
        self,
        latent_dim,
        hidden_size,
        image_tokens_per_img=256,
        initializer_range=0.02,
    ):
        super().__init__()
        self.latent_dim = int(latent_dim)
        self.hidden_size = int(hidden_size)
        self.image_tokens_per_img = int(image_tokens_per_img)
        self.initializer_range = float(initializer_range)
        self.z_proj = nn.Linear(self.latent_dim, self.hidden_size, bias=True)
        self.last_init_stats = None
        self._reset_parameters()

    def _reset_parameters(self):
        # Finalized pure-2D projection initialization.
        weight_std = self.initializer_range / math.sqrt(
            2.0 * float(self.latent_dim)
        )
        init_stats = {
            "init_mode": "pure_2d",
            "z_proj_weight_std": float(weight_std),
            "additive_image_position": False,
        }

        _normal_init_fp32_(self.z_proj.weight, mean=0.0, std=float(weight_std))
        nn.init.zeros_(self.z_proj.bias)
        self.last_init_stats = init_stats

    def _reset_image_slots(self):
        self._reset_parameters()

    @property
    def weight_dtype(self):
        return self.z_proj.weight.dtype

    def embed_latents(self, latents):
        x = latents.to(dtype=self.z_proj.weight.dtype)
        return self.z_proj(x)

    def embed_mask(
        self,
        shape,
        mask_embedding,
        *,
        debug_finite: bool = False,
        debug_label: str = "",
    ):
        x = mask_embedding.to(dtype=self.z_proj.weight.dtype)
        return x.expand(tuple(shape) + (x.shape[-1],))

    def forward(self, latents):
        return self.embed_latents(latents)


def _compute_default_rope_parameters(config: Qwen3Config, device=None):
    base = getattr(config, "rope_theta", 10000.0)
    head_dim = getattr(
        config, "head_dim", config.hidden_size // config.num_attention_heads
    )
    partial_rotary_factor = getattr(config, "partial_rotary_factor", 1.0)
    dim = int(head_dim * partial_rotary_factor)
    inv_freq = 1.0 / (
        base ** (torch.arange(0, dim, 2, dtype=torch.float32, device=device) / dim)
    )
    return inv_freq, 1.0


@use_kernel_forward_from_hub("RMSNorm")
class Qwen3RMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        Qwen3RMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        if getattr(hidden_states, "is_npu", False):
            return torch_npu.npu_rms_norm(
                hidden_states, self.weight, epsilon=self.variance_epsilon
            )[0]
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class Qwen3MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(X0_q, XT_q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    X0_q_embed = (X0_q * cos) + (rotate_half(X0_q) * sin)
    XT_q_embed = (XT_q * cos) + (rotate_half(XT_q) * sin) if XT_q is not None else None
    k_embed = (k * cos) + (rotate_half(k) * sin)

    return X0_q_embed, XT_q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(
        batch, num_key_value_heads, n_rep, slen, head_dim
    )
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def _debug_require_finite_tensor(
    enabled: bool,
    label: str,
    component: str,
    tensor: torch.Tensor | None,
) -> None:
    if not enabled or tensor is None:
        return
    finite = torch.isfinite(tensor)
    if bool(finite.all()):
        return
    finite_values = tensor[finite].float()
    nonfinite_rows = None
    nonfinite_axis1 = None
    nonfinite_last_dim = None
    if tensor.ndim >= 1:
        row_finite = finite.reshape(tensor.shape[0], -1).all(dim=1)
        row_indices = (~row_finite).nonzero(as_tuple=True)[0].detach().cpu().tolist()
        nonfinite_rows = {
            "count": len(row_indices),
            "first": row_indices[:64],
        }
    if tensor.ndim >= 2:
        axis1_nonfinite = (
            (~finite).movedim(1, 0).reshape(tensor.shape[1], -1).any(dim=1)
        )
        axis1_indices = (
            axis1_nonfinite.nonzero(as_tuple=True)[0].detach().cpu().tolist()
        )
        nonfinite_axis1 = {
            "count": len(axis1_indices),
            "first": axis1_indices[:64],
        }
        last_nonfinite = (~finite).reshape(-1, tensor.shape[-1]).any(dim=0)
        last_indices = last_nonfinite.nonzero(as_tuple=True)[0].detach().cpu().tolist()
        nonfinite_last_dim = {
            "count": len(last_indices),
            "first": last_indices[:64],
        }
    finite_range = (
        [float(finite_values.min().item()), float(finite_values.max().item())]
        if finite_values.numel()
        else None
    )
    raise FloatingPointError(
        "non-finite tensor inside selfless-flow backbone: "
        f"label={label!r}, component={component!r}, shape={tuple(tensor.shape)}, "
        f"nonfinite_rows={nonfinite_rows}, "
        f"nonfinite_axis1={nonfinite_axis1}, nonfinite_last_dim={nonfinite_last_dim}, "
        f"nonfinite={int((~finite).sum().item())}/{tensor.numel()}, "
        f"finite_range={finite_range}, "
        f"finite_max_abs={float(finite_values.abs().max().item()) if finite_values.numel() else None}"
    )


def compute_image_local_positions(
    token_types: torch.Tensor,
    image_tokens_per_img: int,
) -> torch.Tensor:
    is_image = token_types == 1
    local_positions = torch.full(
        token_types.shape,
        -1,
        device=token_types.device,
        dtype=torch.long,
    )
    if not is_image.any():
        return local_positions

    for batch_idx in range(is_image.shape[0]):
        positions = is_image[batch_idx].nonzero(as_tuple=True)[0]
        if positions.numel() == 0:
            continue
        gaps = (positions[1:] != positions[:-1] + 1).nonzero(as_tuple=True)[0] + 1
        boundaries = torch.cat(
            [
                torch.zeros(1, device=positions.device, dtype=torch.long),
                gaps,
                torch.full(
                    (1,), positions.numel(), device=positions.device, dtype=torch.long
                ),
            ]
        )
        for start_idx, end_idx in zip(
            boundaries[:-1].tolist(), boundaries[1:].tolist()
        ):
            span = positions[start_idx:end_idx]
            span_len = span.numel()
            if span_len > image_tokens_per_img:
                raise ValueError(
                    f"image span length {span_len} exceeds image_tokens_per_img={image_tokens_per_img}"
                )
            local_positions[batch_idx, span] = torch.arange(
                span_len,
                device=token_types.device,
                dtype=torch.long,
            )
    return local_positions


def _to_bool_atten_mask(attention_mask) -> tuple[torch.Tensor, torch.Tensor]:
    """Convert a stored dense additive/bool mask into npu_fusion_attention bool mask (True = disallow).

    npu_fusion_attention 在全 mask 行（所有 kv 均 disallow）上会产生 NaN/垃圾值，
    而 FlexAttention 对这些行返回严格的 0。这里先放行 kv[0] 避免 NaN，再由
    调用方使用 valid_rows 将输出恢复为严格的 0。

    无 sync 版本：始终在 GPU 上执行 clamp，避免 bool(row_all.any()) 的
    device→host sync（每层 2 次 × 28 层 = 56 次 sync，~200ms/step）。
    """
    if attention_mask.dtype == torch.bool:
        mask = attention_mask
    else:
        mask = attention_mask < 0
    row_all = mask.all(dim=-1, keepdim=True)
    # 无条件执行：对非全 mask 行是 no-op（mask[..., 0] & True = mask[..., 0]）
    mask = mask.clone()
    mask[..., 0] = mask[..., 0] & ~row_all.squeeze(-1)
    return mask, ~row_all


def _fill_invalid_token_types(
    token_types: torch.Tensor,
    valid_mask: torch.Tensor,
) -> torch.Tensor:
    """Replace invalid token types without uint8 ``masked_fill`` on Ascend."""
    return torch.where(
        valid_mask,
        token_types,
        torch.full_like(token_types, 3),
    )


def compiled_flex_attention(query, key, value, attention_mask, scaling, enable_gqa):
    """Dispatch attention to fused NPU or reference flex-attention kernels.

    attention_mask: dense bool/additive mask，形状 [B, 1|H, Q_LEN, KV_LEN]，
    True 或 -inf 表示禁止 attend（与 flex_attention BlockMask 语义相反，已在
    get_selfless_mask 侧转换好）。
    """
    if query.device.type != "npu":
        return flex_attention(
            query=query,
            key=key,
            value=value,
            block_mask=attention_mask,
            scale=scaling,
            enable_gqa=enable_gqa,
            return_lse=False,
        )

    # npu_fusion_attention 原生支持 Nq/Nkv 为正整数的 GQA；保留紧凑 KV heads，
    # 避免 repeat_interleave 的额外显存、带宽和反向归并开销。
    if isinstance(attention_mask, tuple):
        if len(attention_mask) != 2:
            raise ValueError(
                "prepared attention_mask must contain (safe_mask, valid_rows)"
            )
        safe_mask, valid_rows = attention_mask
    else:
        safe_mask, valid_rows = _to_bool_atten_mask(attention_mask)
    out = torch_npu.npu_fusion_attention(
        query,
        key,
        value,
        head_num=query.shape[1],
        input_layout="BNSD",
        atten_mask=safe_mask,
        sparse_mode=0,
        scale=scaling,
    )
    return out[0] * valid_rows.to(dtype=out[0].dtype)


class Qwen3Attention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: Qwen3Config, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(
            config, "head_dim", config.hidden_size // config.num_attention_heads
        )
        self.num_key_value_groups = (
            config.num_attention_heads // config.num_key_value_heads
        )
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        gate_mode = str(
            getattr(config, "backbone_attention_output_gate", "none")
        ).strip().lower()
        if gate_mode not in {"none", "per_head_identity_sigmoid"}:
            raise ValueError(
                "backbone_attention_output_gate must be one of "
                "{'none', 'per_head_identity_sigmoid'}, "
                f"got {gate_mode!r}."
            )
        self.backbone_attention_output_gate = gate_mode
        self.backbone_attention_gate_scale = 2.0
        self.last_gate_stats: dict[str, torch.Tensor] = {}

        self.q_proj = nn.Linear(
            config.hidden_size,
            config.num_attention_heads * self.head_dim,
            bias=config.attention_bias,
        )
        self.k_proj = nn.Linear(
            config.hidden_size,
            config.num_key_value_heads * self.head_dim,
            bias=config.attention_bias,
        )
        self.v_proj = nn.Linear(
            config.hidden_size,
            config.num_key_value_heads * self.head_dim,
            bias=config.attention_bias,
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim,
            config.hidden_size,
            bias=config.attention_bias,
        )
        self.q_norm = Qwen3RMSNorm(
            self.head_dim, eps=config.rms_norm_eps
        )  # unlike olmo, only on the head dim!
        self.k_norm = Qwen3RMSNorm(
            self.head_dim, eps=config.rms_norm_eps
        )  # thus post q_norm does not need reshape
        if self.backbone_attention_output_gate != "none":
            # nn.Linear initializes its weight randomly. Restore the CPU RNG after
            # construction so enabling the identity gate cannot perturb the
            # initialization of any pre-existing downstream module.
            with torch.random.fork_rng(devices=[]):
                self.attn_output_gate_proj = nn.Linear(
                    config.hidden_size,
                    config.num_attention_heads,
                    bias=False,
                )
            self.reset_attention_output_gate()
        else:
            self.attn_output_gate_proj = None

    def reset_attention_output_gate(self) -> None:
        if self.attn_output_gate_proj is None:
            return
        with torch.no_grad():
            nn.init.zeros_(self.attn_output_gate_proj.weight)

    @staticmethod
    def _gate_summary(
        gate: torch.Tensor,
        *,
        prefix: str,
    ) -> dict[str, torch.Tensor]:
        values = gate.detach().float()
        return {
            f"{prefix}/mean": values.mean(),
            f"{prefix}/std": values.std(unbiased=False),
            f"{prefix}/mean_abs_delta": (values - 1.0).abs().mean(),
            f"{prefix}/saturation_low": (values < 0.1).float().mean(),
            f"{prefix}/saturation_high": (values > 1.9).float().mean(),
        }

    @staticmethod
    def _masked_gate_mean(
        gate: torch.Tensor,
        mask: torch.Tensor,
    ) -> torch.Tensor:
        mask = mask.to(device=gate.device, dtype=torch.bool)
        values = gate.detach().float()
        while mask.ndim < values.ndim:
            mask = mask.unsqueeze(-1)
        mask = mask.expand_as(values)
        weights = mask.to(dtype=values.dtype)
        return (values * weights).sum() / weights.sum().clamp_min(1.0)

    def _record_gate_stats(
        self,
        gate: torch.Tensor,
        *,
        stream: str,
        token_types: torch.Tensor | None,
        flow_sigma: torch.Tensor | None,
        detailed: bool,
    ) -> None:
        self.last_gate_stats.update(self._gate_summary(gate, prefix=stream))
        if not detailed or token_types is None:
            return

        token_types = token_types.to(device=gate.device)
        for token_type, label in (
            (0, "text"),
            (1, "image"),
            (2, "special"),
            (3, "padding"),
        ):
            value = self._masked_gate_mean(gate, token_types.eq(token_type))
            if value is not None:
                self.last_gate_stats[f"{stream}/{label}/mean"] = value

        if flow_sigma is None:
            return
        flow_sigma = flow_sigma.to(device=gate.device, dtype=torch.float32)
        if tuple(flow_sigma.shape) != tuple(token_types.shape):
            raise ValueError(
                "flow_sigma must align with token_types when detailed backbone "
                f"gate statistics are requested: {tuple(flow_sigma.shape)} != "
                f"{tuple(token_types.shape)}."
            )
        image_mask = token_types.eq(1)
        positive_inf = torch.full_like(flow_sigma, torch.inf)
        negative_inf = torch.full_like(flow_sigma, -torch.inf)
        row_min = torch.where(image_mask, flow_sigma, positive_inf).amin(
            dim=1, keepdim=True
        )
        row_max = torch.where(image_mask, flow_sigma, negative_inf).amax(
            dim=1, keepdim=True
        )
        relative_order = (flow_sigma - row_min) / (row_max - row_min).clamp_min(
            1.0e-12
        )
        for quartile in range(4):
            lower = quartile / 4.0
            upper = (quartile + 1) / 4.0
            if quartile == 3:
                quartile_mask = image_mask & relative_order.ge(lower)
            else:
                quartile_mask = (
                    image_mask
                    & relative_order.ge(lower)
                    & relative_order.lt(upper)
                )
            value = self._masked_gate_mean(gate, quartile_mask)
            if value is not None:
                self.last_gate_stats[
                    f"{stream}/image_order_q{quartile + 1}/mean"
                ] = value

    def _apply_attention_output_gate(
        self,
        attention_output: torch.Tensor | None,
        hidden_states: torch.Tensor | None,
        *,
        stream: str,
        token_types: torch.Tensor | None,
        flow_sigma: torch.Tensor | None,
        record_stats: bool,
        detailed_stats: bool,
    ) -> torch.Tensor | None:
        if attention_output is None or hidden_states is None:
            return attention_output
        if self.attn_output_gate_proj is None:
            return attention_output
        gate = (
            torch.sigmoid(self.attn_output_gate_proj(hidden_states))
            * self.backbone_attention_gate_scale
        )
        if record_stats:
            self._record_gate_stats(
                gate,
                stream=stream,
                token_types=token_types,
                flow_sigma=flow_sigma,
                detailed=detailed_stats,
            )
        return attention_output * gate.transpose(1, 2).unsqueeze(-1)

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: torch.Tensor,
        content_attention_mask: torch.Tensor | None = None,
        past_key_values: Optional[Cache] = None,
        cache_read_only: bool = False,
        cache_write_mask: Optional[torch.BoolTensor] = None,
        cache_write_prefix: Optional[int] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        debug_finite = bool(kwargs.pop("debug_finite_backbone", False))
        debug_label = str(kwargs.pop("debug_backbone_label", ""))
        record_gate_stats = bool(
            kwargs.pop("record_backbone_gate_stats", False)
        )
        detailed_gate_stats = (
            str(kwargs.pop("backbone_gate_stats_level", "summary")).strip().lower()
            == "detailed"
        )
        self.last_gate_stats.clear()
        prefix = f"layers.{self.layer_idx}.self_attn"
        _debug_require_finite_tensor(
            debug_finite,
            debug_label,
            f"{prefix}.input_x0",
            X0_hidden_states,
        )
        input_shape = X0_hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        XT_query_states = (
            self.q_proj(XT_hidden_states).view(hidden_shape)
            if XT_hidden_states is not None
            else None
        )
        X0_query_states = self.q_proj(X0_hidden_states).view(hidden_shape)
        X0_key_states = self.k_proj(X0_hidden_states).view(hidden_shape)
        X0_value_states = self.v_proj(X0_hidden_states).view(hidden_shape)
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.q_proj", X0_query_states
        )
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.k_proj", X0_key_states
        )
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.v_proj", X0_value_states
        )
        XT_query_states = (
            self.q_norm(XT_query_states).transpose(1, 2)
            if XT_query_states is not None
            else None
        )
        X0_query_states = self.q_norm(X0_query_states).transpose(1, 2)
        X0_key_states = self.k_norm(X0_key_states).transpose(1, 2)
        X0_value_states = X0_value_states.transpose(1, 2)
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.q_norm", X0_query_states
        )
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.k_norm", X0_key_states
        )

        cos, sin = position_embeddings
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.rope_cos", cos
        )
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.rope_sin", sin
        )
        (
            X0_query_states,
            XT_query_states,
            X0_key_states,
        ) = apply_rotary_pos_emb(
            X0_query_states, XT_query_states, X0_key_states, cos, sin
        )
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.rotary_q", X0_query_states
        )
        _debug_require_finite_tensor(
            debug_finite, debug_label, f"{prefix}.rotary_k", X0_key_states
        )

        if past_key_values is not None and cache_read_only:
            cache_layer = past_key_values.layers[self.layer_idx]
            if not cache_layer.is_initialized:
                raise RuntimeError(
                    "Cannot read an uninitialized backbone KV cache at "
                    f"layer {self.layer_idx}."
                )
            X0_key_states, X0_value_states = past_key_values.read(self.layer_idx)
        elif past_key_values is not None:
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            cache_kwargs = {
                "sin": sin,
                "cos": cos,
                "cache_position": cache_position,
                "cache_write_mask": cache_write_mask,
                "cache_write_prefix": cache_write_prefix,
            }
            X0_key_states, X0_value_states = past_key_values.update(
                X0_key_states, X0_value_states, self.layer_idx, cache_kwargs
            )

        # 检查是否需要 GQA (Grouped Query Attention)
        enable_gqa = self.config.num_attention_heads != self.config.num_key_value_heads
        x0_attention_mask = (
            attention_mask
            if content_attention_mask is None
            else content_attention_mask
        )

        X0_attn_output = compiled_flex_attention(
            X0_query_states,
            X0_key_states,
            X0_value_states,
            x0_attention_mask,
            self.scaling,
            enable_gqa,
        )
        XT_attn_output = (
            compiled_flex_attention(
                XT_query_states,
                X0_key_states,
                X0_value_states,
                attention_mask,
                self.scaling,
                enable_gqa,
            )
            if XT_query_states is not None
            else None
        )
        attn_weights = None

        _debug_require_finite_tensor(
            debug_finite,
            debug_label,
            f"{prefix}.flex_attention_output",
            X0_attn_output,
        )
        _debug_require_finite_tensor(
            debug_finite,
            debug_label,
            f"{prefix}.flex_attention_output_xt",
            XT_attn_output,
        )

        X0_attn_output = self._apply_attention_output_gate(
            X0_attn_output,
            X0_hidden_states,
            stream="x0",
            token_types=kwargs.get("token_types", None),
            flow_sigma=kwargs.get("flow_sigma", None),
            record_stats=record_gate_stats,
            detailed_stats=detailed_gate_stats,
        )
        XT_attn_output = self._apply_attention_output_gate(
            XT_attn_output,
            XT_hidden_states,
            stream="xt",
            token_types=kwargs.get("token_types", None),
            flow_sigma=kwargs.get("flow_sigma", None),
            record_stats=record_gate_stats,
            detailed_stats=detailed_gate_stats,
        )

        # attn_output 形状: (batch, heads, seq_len, head_dim)
        # 需要转换回 (batch, seq_len, hidden_size)
        X0_attn_output = (
            X0_attn_output.transpose(1, 2).reshape(*input_shape, -1).contiguous()
        )
        XT_attn_output = (
            XT_attn_output.transpose(1, 2).reshape(*input_shape, -1).contiguous()
            if XT_attn_output is not None
            else None
        )
        X0_attn_output = self.o_proj(X0_attn_output)
        XT_attn_output = (
            self.o_proj(XT_attn_output) if XT_attn_output is not None else None
        )
        _debug_require_finite_tensor(
            debug_finite,
            debug_label,
            f"{prefix}.o_proj",
            X0_attn_output,
        )

        return X0_attn_output, XT_attn_output, attn_weights


class Qwen3DecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: Qwen3Config, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = Qwen3Attention(config=config, layer_idx=layer_idx)

        self.mlp = Qwen3MLP(config)
        self.input_layernorm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = Qwen3RMSNorm(
            config.hidden_size, eps=config.rms_norm_eps
        )
        self.attention_type = config.layer_types[layer_idx]

    @deprecate_kwarg("past_key_value", new_name="past_key_values", version="4.58")
    def forward(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        content_attention_mask: torch.Tensor | None = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[
            tuple[torch.Tensor, torch.Tensor]
        ] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        X0_residual = X0_hidden_states
        XT_residual = XT_hidden_states if XT_hidden_states is not None else None
        X0_hidden_states = self.input_layernorm(X0_hidden_states)
        XT_hidden_states = (
            self.input_layernorm(XT_hidden_states)
            if XT_hidden_states is not None
            else None
        )
        # Self Attention
        X0_hidden_states, XT_hidden_states, _ = self.self_attn(
            X0_hidden_states=X0_hidden_states,
            XT_hidden_states=XT_hidden_states,
            attention_mask=attention_mask,
            content_attention_mask=content_attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        X0_hidden_states = X0_residual + X0_hidden_states
        XT_hidden_states = (
            XT_residual + XT_hidden_states if XT_hidden_states is not None else None
        )

        # Fully Connected
        X0_residual = X0_hidden_states
        XT_residual = XT_hidden_states if XT_hidden_states is not None else None
        X0_hidden_states = self.post_attention_layernorm(X0_hidden_states)
        XT_hidden_states = (
            self.post_attention_layernorm(XT_hidden_states)
            if XT_hidden_states is not None
            else None
        )
        X0_hidden_states = self.mlp(X0_hidden_states)
        XT_hidden_states = (
            self.mlp(XT_hidden_states) if XT_hidden_states is not None else None
        )
        X0_hidden_states = X0_residual + X0_hidden_states
        XT_hidden_states = (
            XT_residual + XT_hidden_states if XT_hidden_states is not None else None
        )
        return X0_hidden_states, XT_hidden_states


@auto_docstring
class Qwen3PreTrainedModel(PreTrainedModel):
    config: Qwen3Config
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["Qwen3DecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": Qwen3DecoderLayer,
        "attentions": Qwen3Attention,
    }


class Qwen3RotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    @staticmethod
    def compute_default_rope_parameters(config: Qwen3Config, device=None):
        return _compute_default_rope_parameters(config, device)

    def __init__(self, config: Qwen3Config, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and isinstance(config.rope_scaling, dict):
            self.rope_type = config.rope_scaling.get(
                "rope_type", config.rope_scaling.get("type")
            )
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        if self.rope_type in (None, "default"):
            self.rope_init_fn = ROPE_INIT_FUNCTIONS.get(
                "default", _compute_default_rope_parameters
            )
        else:
            self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        if position_ids.ndim == 2:
            inv_freq_expanded = (
                self.inv_freq[None, :, None]
                .float()
                .expand(position_ids.shape[0], -1, 1)
                .to(x.device)
            )
            position_ids_expanded = position_ids[:, None, :].float()
        elif position_ids.ndim == 3 and position_ids.shape[0] == 2:
            num_frequency_pairs = int(self.inv_freq.numel())
            coordinate_axes = (
                torch.arange(
                    num_frequency_pairs,
                    device=position_ids.device,
                    dtype=torch.long,
                )
                % 2
            )
            selected_positions = position_ids.index_select(0, coordinate_axes).permute(
                1, 0, 2
            )
            inv_freq_expanded = (
                self.inv_freq[None, :, None]
                .float()
                .expand(position_ids.shape[1], -1, 1)
                .to(x.device)
            )
            position_ids_expanded = selected_positions.float()
        else:
            raise ValueError(
                f"position_ids must have shape [B,L] or [2,B,L], got {tuple(position_ids.shape)}"
            )

        device_type = (
            x.device.type
            if isinstance(x.device.type, str) and x.device.type != "mps"
            else "cpu"
        )
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            if position_ids.ndim == 2:
                freqs = (
                    inv_freq_expanded.float() @ position_ids_expanded.float()
                ).transpose(1, 2)
            else:
                freqs = (
                    inv_freq_expanded.float() * position_ids_expanded.float()
                ).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class Qwen3Model(Qwen3PreTrainedModel):
    supported_training_objectives = frozenset({"selfless_dual_stream"})

    def __init__(self, config: Qwen3Config):
        validate_model_image_layout(config)
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size
        self.training_objective = str(
            getattr(config, "training_objective", "selfless_dual_stream")
        ).strip().lower()
        if self.training_objective not in self.supported_training_objectives:
            raise ValueError(
                "training_objective must be selfless_dual_stream, "
                f"got {self.training_objective!r}"
            )

        self.image_latent_dim = int(
            getattr(config, "image_latent_dim", CANONICAL_IMAGE_LATENT_DIM)
        )
        image_tokens_per_img = int(
            getattr(config, "image_tokens_per_img", CANONICAL_IMAGE_TOKENS)
        )
        self.embed_tokens = nn.Embedding(
            config.vocab_size, config.hidden_size, self.padding_idx
        )
        self.image_token_embedder = ImageTokenEmbedder(
            latent_dim=self.image_latent_dim,
            hidden_size=config.hidden_size,
            image_tokens_per_img=image_tokens_per_img,
            initializer_range=getattr(config, "initializer_range", 0.02),
        )
        self.image_input_noise_strength = float(
            getattr(config, "image_input_noise_strength", 1.0e-2)
        )
        self.layers = nn.ModuleList(
            [
                Qwen3DecoderLayer(config, layer_idx)
                for layer_idx in range(config.num_hidden_layers)
            ]
        )
        self.norm = Qwen3RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = Qwen3RotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()
        self.reset_backbone_attention_output_gates()
        self.reset_image_token_embedder()

    def reset_backbone_attention_output_gates(self) -> None:
        for layer in self.layers:
            layer.self_attn.reset_attention_output_gate()

    def backbone_attention_gate_stats(self) -> dict[str, torch.Tensor]:
        stats: dict[str, torch.Tensor] = {}
        for layer_idx, layer in enumerate(self.layers):
            for name, value in layer.self_attn.last_gate_stats.items():
                stats[f"backbone_gate/layer_{layer_idx:02d}/{name}"] = value
        return stats

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, new_embeddings):
        self.embed_tokens = new_embeddings

    def reset_image_token_embedder(self):
        self.image_token_embedder._reset_parameters()
        return self.image_token_embedder.last_init_stats

    def _image_mask_token_id(self) -> int:
        return int(
            getattr(self.config, "image_mask_token_id", self.config.mask_token_id)
        )

    def _image_mask_embedding(self, device, dtype):
        token_id = self._image_mask_token_id()
        if token_id < 0 or token_id >= self.embed_tokens.num_embeddings:
            raise ValueError(
                f"image_mask_token_id={token_id} is outside embedding vocab size "
                f"{self.embed_tokens.num_embeddings}."
            )
        token = torch.tensor([token_id], device=device, dtype=torch.long)
        return self.embed_tokens(token)[0].to(dtype=dtype)

    def image_local_positions(self, token_types: torch.Tensor) -> torch.Tensor:
        return compute_image_local_positions(
            token_types,
            self.image_token_embedder.image_tokens_per_img,
        )

    def _validate_image_latents(self, image_latents: torch.Tensor):
        if image_latents.shape[-1] != self.image_latent_dim:
            raise ValueError(
                f"image_latents last dimension ({image_latents.shape[-1]}) must match "
                f"config.image_latent_dim ({self.image_latent_dim})."
            )

    def _maybe_add_image_input_noise(self, image_latents: torch.Tensor) -> torch.Tensor:
        strength = self.image_input_noise_strength
        if not self.training or strength <= 0.0:
            return image_latents
        return image_latents + torch.randn_like(image_latents) * float(strength)

    def _build_x0_inputs_embeds(
        self,
        input_ids: torch.LongTensor,
        token_types: torch.Tensor | None,
        image_latents: torch.Tensor | None,
        image_latent_mask: torch.Tensor | None,
        image_spans_present: bool | None = None,
        image_latents_are_noisy: bool = False,
        debug_finite: bool = False,
        debug_label: str = "",
        image_context: dict | None = None,
    ) -> torch.Tensor:
        if token_types is None:
            return self.embed_tokens(input_ids)

        token_types = token_types.to(input_ids.device)
        is_image = token_types == 1
        safe_input_ids = input_ids.masked_fill(is_image, self._image_mask_token_id())
        inputs_embeds = self.embed_tokens(safe_input_ids)
        _debug_require_finite_tensor(
            debug_finite,
            debug_label,
            "input_embeddings.safe_token_lookup",
            inputs_embeds,
        )

        has_image = image_spans_present
        if has_image is None:
            has_image = bool(is_image.any())
        if has_image:
            if image_latents is None:
                raise ValueError(
                    "image_latents must be provided when token_types contains image tokens."
                )
            self._validate_image_latents(image_latents)
            image_latents = image_latents.to(
                device=input_ids.device,
                dtype=self.image_token_embedder.weight_dtype,
            )
            projected_latents = self.image_token_embedder(
                self._maybe_add_image_input_noise(image_latents)
                if not image_latents_are_noisy
                else image_latents
            ).to(dtype=inputs_embeds.dtype)
            if image_latent_mask is None:
                inputs_embeds = torch.where(
                    is_image.unsqueeze(-1),
                    projected_latents,
                    inputs_embeds,
                )
            else:
                image_latent_mask = image_latent_mask.to(
                    device=input_ids.device, dtype=torch.bool
                )
                use_image_latent = is_image & image_latent_mask
                use_image_mask = is_image & ~use_image_latent
                image_mask_embedding = self._image_mask_embedding(
                    device=input_ids.device,
                    dtype=self.image_token_embedder.weight_dtype,
                )
                _debug_require_finite_tensor(
                    debug_finite,
                    debug_label,
                    "input_embeddings.image_mask_token",
                    image_mask_embedding,
                )
                image_mask_values = image_mask_embedding.to(
                    dtype=inputs_embeds.dtype
                ).view(1, 1, -1).expand_as(inputs_embeds)
                inputs_embeds = torch.where(
                    use_image_mask.unsqueeze(-1),
                    image_mask_values,
                    inputs_embeds,
                )
                inputs_embeds = torch.where(
                    use_image_latent.unsqueeze(-1),
                    projected_latents,
                    inputs_embeds,
                ).to(dtype=inputs_embeds.dtype)
            _debug_require_finite_tensor(
                debug_finite,
                debug_label,
                "input_embeddings.observed_image_latents",
                projected_latents,
            )
        elif self.training:
            dummy_latent = torch.zeros(
                1,
                self.image_latent_dim,
                device=input_ids.device,
                dtype=self.image_token_embedder.weight_dtype,
            )
            inputs_embeds = (
                inputs_embeds + self.image_token_embedder(dummy_latent).sum() * 0.0
            )

        return inputs_embeds

    def _build_xt_inputs_embeds(
        self,
        input_ids: torch.LongTensor,
        token_types: torch.Tensor | None,
        image_spans_present: bool | None = None,
    ) -> torch.Tensor:
        xt_input_ids = torch.full_like(input_ids, self.config.mask_token_id)
        inputs_embeds = self.embed_tokens(xt_input_ids)
        if token_types is None:
            return inputs_embeds

        token_types = token_types.to(input_ids.device)
        is_image = token_types == 1
        has_image = image_spans_present
        if has_image is None:
            has_image = bool(is_image.any())
        if has_image:
            image_mask_embedding = self._image_mask_embedding(
                device=input_ids.device,
                dtype=self.image_token_embedder.weight_dtype,
            )
            image_mask_values = image_mask_embedding.to(
                dtype=inputs_embeds.dtype
            ).view(1, 1, -1).expand_as(inputs_embeds)
            inputs_embeds = torch.where(
                is_image.unsqueeze(-1),
                image_mask_values,
                inputs_embeds,
            )
        return inputs_embeds

    def _resolve_text_ar_mode(
        self,
        *,
        requested: bool | None,
        calculate_likelihood: bool | None,
        require_image_query_stream: bool | None,
        token_types: torch.Tensor | None,
        image_latent_mask: torch.Tensor | None,
    ) -> bool:
        """Return whether this call uses an ablation-specific text AR stream.

        The production Selfless model never enables this mode.  A dedicated
        ablation model can override the hook without adding a behavior switch
        to the baseline implementation.
        """

        del (
            requested,
            calculate_likelihood,
            require_image_query_stream,
            token_types,
            image_latent_mask,
        )
        return False

    def _needs_query_stream(
        self,
        *,
        calculate_likelihood: bool | None,
        require_image_query_stream: bool | None,
        text_ar_mode: bool,
        image_spans_present: bool | None,
    ) -> bool:
        """Select the XT stream while preserving the baseline default."""

        del require_image_query_stream, text_ar_mode, image_spans_present
        return bool(self.training or calculate_likelihood)

    def _prepare_stream_attention_masks(
        self,
        attention_mask,
        content_attention_mask,
        *,
        text_ar_mode: bool,
        input_ids: torch.LongTensor | None,
        token_types: torch.Tensor | None,
        text_segment_ids: torch.Tensor | None,
        past_key_values: Cache | None,
        cache_position: torch.LongTensor | None,
    ):
        """Allow an isolated model class to supply a text-only content mask."""

        del (
            text_ar_mode,
            input_ids,
            token_types,
            text_segment_ids,
            past_key_values,
            cache_position,
        )
        return attention_mask, content_attention_mask

    def _finalize_stream_hidden(
        self,
        X0_hidden_states: torch.Tensor,
        XT_hidden_states: torch.Tensor | None,
        *,
        use_query_stream: bool,
        text_ar_mode: bool,
        token_types: torch.Tensor | None,
        past_key_values: Cache | None,
        cache_position: torch.LongTensor | None,
    ) -> torch.Tensor:
        """Choose and normalize the stream returned by the baseline model."""

        del text_ar_mode, token_types, past_key_values, cache_position
        hidden_states = XT_hidden_states if use_query_stream else X0_hidden_states
        if hidden_states is None:
            raise RuntimeError("The selected Selfless stream was not constructed.")
        return self.norm(hidden_states)

    # @check_model_inputs
    @auto_docstring
    def forward(
        self,
        X0_input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        content_attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        X0_inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        calculate_likelihood: Optional[bool] = None,
        return_x0_hidden_state: bool = False,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        r"""
        Args:
            X0_input_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Indices of input sequence tokens in the vocabulary.
            attention_mask (`torch.Tensor`, *optional*):
                Attention mask for Flex Attention. Should be a block mask of shape `(batch_size, sequence_length)`.
            calculate_likelihood (`bool`, *optional*):
                Whether to calculate the likelihood of the input sequence. If `True`, the model will compute the likelihood using the XT stream, which is necessary for training. If `False`, the model will only compute the hidden states for the X0 stream, which can be used for efficient decoding.
        """
        if (X0_input_ids is None) ^ (X0_inputs_embeds is not None):
            raise ValueError(
                "You must specify exactly one of input_ids or inputs_embeds"
            )
        if attention_mask is None:
            raise ValueError(
                "attention_mask must be provided for selfless sigma-causal attention."
            )

        require_image_query_stream = kwargs.pop(
            "_require_image_query_stream", None
        )
        requested_text_ar_mode = kwargs.pop("_text_ar_mode", None)
        text_segment_ids = kwargs.pop("_text_segment_ids", None)
        text_ar_mode = self._resolve_text_ar_mode(
            requested=requested_text_ar_mode,
            calculate_likelihood=calculate_likelihood,
            require_image_query_stream=require_image_query_stream,
            token_types=kwargs.get("token_types", None),
            image_latent_mask=kwargs.get("image_latent_mask", None),
        )
        attention_mask, content_attention_mask = (
            self._prepare_stream_attention_masks(
                attention_mask,
                content_attention_mask,
                text_ar_mode=text_ar_mode,
                input_ids=X0_input_ids,
                token_types=kwargs.get("token_types", None),
                text_segment_ids=text_segment_ids,
                past_key_values=past_key_values,
                cache_position=cache_position,
            )
        )

        # Every decoder layer consumes the same dense attention mask, and the
        # X0/XT streams share it as well.  Preparing it inside each attention
        # call repeated all/clone/index operations 56 times per microbatch on
        # the 28-layer training path.  Keep the safe mask and fully-masked-row
        # indicator device-resident and reuse them across all layers/streams.
        if isinstance(attention_mask, torch.Tensor):
            attention_mask = _to_bool_atten_mask(attention_mask)
        if isinstance(content_attention_mask, torch.Tensor):
            content_attention_mask = _to_bool_atten_mask(
                content_attention_mask
            )

        debug_finite_backbone = bool(kwargs.get("debug_finite_backbone", False))
        debug_backbone_label = str(kwargs.get("debug_backbone_label", ""))
        token_types = kwargs.get("token_types", None)
        image_span_table = kwargs.pop("image_span_table", None)
        kwargs.pop("image_local_positions", None)
        image_spans_present = (
            image_span_table.shape[0] > 0
            if image_span_table is not None
            else None
        )

        if X0_inputs_embeds is None:
            X0_inputs_embeds = self._build_x0_inputs_embeds(
                input_ids=X0_input_ids,
                token_types=token_types,
                image_latents=kwargs.get("image_latents", None),
                image_latent_mask=kwargs.get("image_latent_mask", None),
                image_spans_present=image_spans_present,
                image_latents_are_noisy=bool(
                    kwargs.get("image_latents_are_noisy", False)
                ),
                debug_finite=debug_finite_backbone,
                debug_label=debug_backbone_label,
                image_context={
                    "attention_mask": attention_mask,
                    "content_attention_mask": content_attention_mask,
                    "past_key_values": past_key_values,
                    "cache_position": cache_position,
                    "cache_read_only": kwargs.get("cache_read_only", False),
                    "cache_write_prefix": kwargs.get("cache_write_prefix"),
                    "cache_write_mask": kwargs.get("cache_write_mask"),
                    "use_cache": use_cache,
                },
            )
        _debug_require_finite_tensor(
            debug_finite_backbone,
            debug_backbone_label,
            "input_embeddings.x0",
            X0_inputs_embeds,
        )

        use_query_stream = self._needs_query_stream(
            calculate_likelihood=calculate_likelihood,
            require_image_query_stream=require_image_query_stream,
            text_ar_mode=text_ar_mode,
            image_spans_present=image_spans_present,
        )
        if use_query_stream:
            XT_inputs_embeds = self._build_xt_inputs_embeds(
                input_ids=X0_input_ids,
                token_types=token_types,
                image_spans_present=image_spans_present,
            )
        else:
            XT_inputs_embeds = None

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if cache_position is None:
            past_seen_tokens = (
                past_key_values.get_seq_length() if past_key_values is not None else 0
            )
            cache_position = torch.arange(
                past_seen_tokens,
                past_seen_tokens + X0_inputs_embeds.shape[1],
                device=X0_inputs_embeds.device,
            )

        if position_ids is None:
            if token_types is not None:
                position_ids = build_row_col_position_ids(
                    token_types.to(device=X0_inputs_embeds.device),
                    self.image_token_embedder.image_tokens_per_img,
                )
            else:
                position_ids = cache_position.unsqueeze(0)

        X0_hidden_states = X0_inputs_embeds
        XT_hidden_states = XT_inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(X0_hidden_states, position_ids)
        for component_idx, component in enumerate(position_embeddings):
            _debug_require_finite_tensor(
                debug_finite_backbone,
                debug_backbone_label,
                f"rotary_embedding.{component_idx}",
                component,
            )
        for layer_idx, decoder_layer in enumerate(
            self.layers[: self.config.num_hidden_layers]
        ):
            X0_hidden_states, XT_hidden_states = decoder_layer(
                X0_hidden_states,
                XT_hidden_states,
                attention_mask,
                content_attention_mask=content_attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **kwargs,
            )
            _debug_require_finite_tensor(
                debug_finite_backbone,
                debug_backbone_label,
                f"layers.{layer_idx}.output_x0",
                X0_hidden_states,
            )
            _debug_require_finite_tensor(
                debug_finite_backbone,
                debug_backbone_label,
                f"layers.{layer_idx}.output_xt",
                XT_hidden_states,
            )

        hidden_states = self._finalize_stream_hidden(
            X0_hidden_states,
            XT_hidden_states,
            use_query_stream=use_query_stream,
            text_ar_mode=text_ar_mode,
            token_types=token_types,
            past_key_values=past_key_values,
            cache_position=cache_position,
        )
        output = BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
        )
        if return_x0_hidden_state:
            output["x0_last_hidden_state"] = self.norm(X0_hidden_states)
        return output


@auto_docstring
class Qwen3ForCausalLM(
    SelflessGenerationMixin,
    Qwen3PreTrainedModel,
    GenerationMixin,
):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}
    backbone_model_class = Qwen3Model

    def __init__(self, config):
        super().__init__(config)
        flow_condition_contract = str(
            getattr(
                config,
                "flow_condition_contract",
                LEGACY_FLOW_CONDITION_CONTRACT,
            )
        ).strip().lower()
        if flow_condition_contract not in _FLOW_CONDITION_CONTRACTS:
            raise ValueError(
                "unsupported flow_condition_contract="
                f"{flow_condition_contract!r}; expected one of "
                f"{sorted(_FLOW_CONDITION_CONTRACTS)}"
            )
        # Missing metadata identifies historical A/B weights. Persist the
        # resolved legacy contract when they are saved again without changing
        # the instantiated modules or numerical path.
        config.flow_condition_contract = flow_condition_contract
        self.flow_condition_contract = flow_condition_contract
        self.model = self.backbone_model_class(config)
        self.vocab_size = config.vocab_size
        self.image_latent_dim = getattr(config, "image_latent_dim", 4)
        self.image_flow_batch_mul = int(getattr(config, "image_flow_batch_mul", 1))
        self.training_objective = str(
            getattr(config, "training_objective", "selfless_dual_stream")
        ).strip().lower()
        self.lambda_text = float(getattr(config, "lambda_text", 0.0))
        self.lambda_image = float(getattr(config, "lambda_image", 1.0))
        if self.lambda_text < 0.0 or self.lambda_image < 0.0:
            raise ValueError(
                "lambda_text and lambda_image must be non-negative, got "
                f"{self.lambda_text}/{self.lambda_image}"
            )
        if self.lambda_text == 0.0 and self.lambda_image == 0.0:
            raise ValueError("lambda_text and lambda_image cannot both be zero")
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self.image_flow_condition_proj = nn.Linear(
            config.hidden_size, config.hidden_size, bias=True
        )
        self.image_flow_head = FlowLoss(
            target_channels=self.image_latent_dim,
            z_channels=config.hidden_size,
            width=getattr(config, "image_flow_width", 1280),
            depth=getattr(config, "image_flow_depth", 8),
            num_sampling_steps=str(
                getattr(config, "image_flow_num_sampling_steps", "10")
            ),
            grad_checkpointing=getattr(config, "image_flow_grad_checkpointing", False),
            time_scale=getattr(config, "image_flow_time_scale", 1000.0),
            time_sampling=getattr(config, "image_flow_time_sampling", "logit_normal"),
            logit_mean=getattr(config, "image_flow_logit_mean", 0.0),
            logit_std=getattr(config, "image_flow_logit_std", 1.0),
            time_eps=getattr(config, "image_flow_time_eps", 1.0e-4),
            uniform_mix=getattr(config, "image_flow_time_uniform_mix", 0.1),
            solver=getattr(config, "image_flow_solver", "heun"),
            image_tokens_per_img=getattr(config, "image_tokens_per_img", 256),
            # Missing means a checkpoint predates the split flow-head mask
            # contract. Those historical A/B weights were trained with one
            # shared strict mask and must retain their original numerics.
            flow_head_attention_contract=getattr(
                config,
                "flow_head_attention_contract",
                "selfless_strict",
            ),
        )
        if flow_condition_contract == X0_CONTENT_FLOW_CONDITION_CONTRACT:
            # No parameters or buffers are added; therefore initialization RNG,
            # state-dict keys, and checkpoint loading remain identical.
            self.image_flow_head.__class__ = X0ContentFlowLoss

        # Initialize weights and apply final processing
        self.post_init()
        self.reset_backbone_attention_output_gates()
        self.reset_image_modules()

    def reset_backbone_attention_output_gates(self) -> None:
        self.model.reset_backbone_attention_output_gates()

    def reset_image_modules(self) -> None:
        self.image_flow_head.net.initialize_weights()
        self.reset_image_token_embedder()
        self._reset_image_flow_condition_proj()

    @property
    def image_token_embedder(self) -> ImageTokenEmbedder:
        return self.model.image_token_embedder

    def reset_image_token_embedder(self):
        return self.model.reset_image_token_embedder()

    def image_local_positions(self, token_types: torch.Tensor) -> torch.Tensor:
        return self.model.image_local_positions(token_types)

    def _reset_image_flow_condition_proj(self):
        with torch.no_grad():
            std = float(getattr(self.config, "initializer_range", 0.02))
            _normal_init_fp32_(self.image_flow_condition_proj.weight, mean=0.0, std=std)
            nn.init.zeros_(self.image_flow_condition_proj.bias)

    def _prepare_image_flow_condition(
        self,
        z: torch.Tensor,
    ) -> torch.Tensor:
        z = z.to(
            device=self.image_flow_condition_proj.weight.device,
            dtype=self.image_flow_condition_proj.weight.dtype,
        )
        return self.image_flow_condition_proj(z)

    def _uses_backbone_x0_flow_content_condition(self) -> bool:
        """Whether the contextual head uses split XT/X0 AdaLN conditions."""

        return type(self.image_flow_head) is X0ContentFlowLoss

    def _zero_image_module_loss(
        self,
        hidden_states: torch.Tensor,
    ) -> torch.Tensor:
        """Return zero while keeping skipped image modules in the train graph."""

        zero = hidden_states.float().sum() * 0.0
        for module in (self.image_flow_condition_proj, self.image_flow_head):
            for parameter in module.parameters():
                if parameter.requires_grad and parameter.numel() > 0:
                    zero = zero + parameter.reshape(-1)[0].float() * 0.0
        self.image_flow_head.last_forward_stats = {}
        return zero

    def _shared_noisy_image_latents(
        self,
        image_latents: torch.Tensor | None,
        token_types: torch.Tensor | None,
    ) -> torch.Tensor | None:
        if image_latents is None:
            return None
        if not self.training:
            return image_latents
        return self.model._maybe_add_image_input_noise(image_latents)

    def sample_image_flow_with_cfg(
        self,
        z: torch.Tensor,
        z_uncond: torch.Tensor | None = None,
        temperature: float = 1.0,
        cfg: float = 1.0,
        cfg_schedule: str = "constant",
        solver: str | None = None,
        num_steps: int | None = None,
        context_latents: torch.Tensor | None = None,
        context_mask: torch.Tensor | None = None,
        content_attention_mask: torch.Tensor | None = None,
        query_positions: torch.Tensor | None = None,
        context_positions: torch.Tensor | None = None,
        context_conditions: torch.Tensor | None = None,
        latent_mixer_cache: dict | None = None,
        latent_mixer_cache_is_paired: bool = False,
        pending_context_latents: torch.Tensor | None = None,
        pending_context_conditions: torch.Tensor | None = None,
        pending_context_positions: torch.Tensor | None = None,
        context_prepared: bool = False,
        initial_noise: torch.Tensor | None = None,
        initial_noise_prevalidated: bool = False,
        condition_evaluator=None,
        debug_finite: bool = False,
        debug_label: str = "",
    ) -> torch.Tensor:
        if cfg != 1.0:
            if z_uncond is None:
                raise ValueError(
                    "cfg != 1.0 requires paired conditional/unconditional conditions"
                )
            if z.shape != z_uncond.shape:
                raise ValueError(
                    "z and z_uncond must have the same shape, got "
                    f"{tuple(z.shape)} and {tuple(z_uncond.shape)}"
                )
            z = torch.cat([z, z_uncond], dim=0)
        return self.image_flow_head.sample(
            z,
            temperature=temperature,
            cfg=cfg,
            cfg_schedule=cfg_schedule,
            solver=solver,
            num_steps=num_steps,
            context_latents=context_latents,
            context_mask=context_mask,
            content_attention_mask=content_attention_mask,
            query_positions=query_positions,
            context_positions=context_positions,
            context_conditions=context_conditions,
            latent_mixer_cache=latent_mixer_cache,
            latent_mixer_cache_is_paired=latent_mixer_cache_is_paired,
            pending_context_latents=pending_context_latents,
            pending_context_conditions=pending_context_conditions,
            pending_context_positions=pending_context_positions,
            context_prepared=context_prepared,
            initial_noise=initial_noise,
            initial_noise_prevalidated=initial_noise_prevalidated,
            condition_evaluator=condition_evaluator,
            debug_finite=debug_finite,
            debug_label=debug_label,
        )

    def _make_backbone_flow_condition_evaluator(self, **_generation_state):
        """Optional inference hook; the default static model keeps fixed ``z``."""

        return None

    def tie_weights(
        self, missing_keys: set[str] | None = None, recompute_mapping: bool = True
    ):
        # Delegate standard tie (lm_head ↔ embed_tokens) to parent
        super().tie_weights(
            missing_keys=missing_keys, recompute_mapping=recompute_mapping
        )

    def _prepare_backbone_forward_kwargs(
        self,
        model_kwargs: dict,
        *,
        compute_text_loss: bool,
        compute_image_loss: bool,
    ) -> dict:
        """Extension hook used by isolated objective model classes."""

        del compute_text_loss, compute_image_loss
        return model_kwargs

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        X0_input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        image_latents: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        calculate_likelihood: bool = False,
        **kwargs: Unpack[TransformersKwargs],
    ) -> CausalLMOutputWithPast:
        r"""
        Args:
            X0_input_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Indices of input sequence tokens in the vocabulary. The input sequence should be formatted as
                `[X0_1, X0_2, ..., X0_n]`, where `X0_i` represents the visible content token for the i-th
                position. If `inputs_embeds` is not provided, this argument will be used to
                compute the input embeddings.
            attention_mask (`torch.Tensor`, *optional*):
                Attention mask for selfless sigma-causal attention. The mask should be designed such that
                query positions can only attend to key/value positions with lower sigma.
            labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Enables training loss. With `token_types`, non-ignored text
                labels are combined with masked image-flow loss according to
                `lambda_text` and `lambda_image`.
            image_latents (`torch.FloatTensor` of shape `(batch_size, sequence_length, image_latent_dim)`, *optional*):
                Continuous VAE latent tokens aligned with `token_types == 1` positions.
            calculate_likelihood (`bool`, *optional*, defaults to `False`):
                Whether to calculate the likelihood of the input sequence. If `True`, the model will compute the likelihood using the XT stream, which is necessary for training. If `False`, the model will only compute the hidden states for the X0 stream, which can be used for efficient decoding. Note that when `calculate_likelihood` is `True`, the model will return the likelihood loss in the `loss` field of the output, and the `logits` field will contain the logits from the XT stream.
        ```"""
        calculate_likelihood = calculate_likelihood or labels is not None
        return_logits = bool(kwargs.pop("return_logits", True))
        model_kwargs = dict(kwargs)
        return_per_modality_loss_graph = bool(
            model_kwargs.pop("return_per_modality_loss_graph", False)
        )
        compute_text_loss = bool(
            model_kwargs.pop("compute_text_loss", True)
        )
        compute_image_loss_arg = model_kwargs.pop(
            "compute_image_loss", None
        )
        image_loss_mask_arg = model_kwargs.pop("image_loss_mask", None)
        image_latent_mask_arg = model_kwargs.get("image_latent_mask", None)
        image_span_table_arg = model_kwargs.get("image_span_table", None)
        image_local_positions_arg = model_kwargs.get(
            "image_local_positions", None
        )
        record_flow_stats = bool(model_kwargs.pop("record_flow_stats", True))
        compute_image_loss = (
            bool(compute_image_loss_arg)
            if compute_image_loss_arg is not None
            else bool(
                image_span_table_arg is not None
                and image_span_table_arg.shape[0] > 0
            )
        )
        clean_image_latents = image_latents
        if inputs_embeds is None:
            context_image_latents = self._shared_noisy_image_latents(
                clean_image_latents,
                model_kwargs.get("token_types", None),
            )
        else:
            context_image_latents = clean_image_latents
        image_latents_for_model = (
            context_image_latents
            if context_image_latents is not None
            else clean_image_latents
        )
        if (
            context_image_latents is not None
            and context_image_latents is not clean_image_latents
        ):
            model_kwargs["image_latents_are_noisy"] = True
        model_kwargs = self._prepare_backbone_forward_kwargs(
            model_kwargs,
            compute_text_loss=compute_text_loss,
            compute_image_loss=compute_image_loss,
        )
        use_x0_content_condition = bool(
            labels is not None
            and compute_image_loss
            and self._uses_backbone_x0_flow_content_condition()
        )
        if use_x0_content_condition:
            model_kwargs["return_x0_hidden_state"] = True
        outputs: BaseModelOutputWithPast = self.model(
            X0_input_ids=X0_input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            X0_inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            cache_position=cache_position,
            calculate_likelihood=calculate_likelihood,
            image_latents=image_latents_for_model,
            **model_kwargs,
        )

        hidden_states = outputs.last_hidden_state
        slice_indices = (
            slice(-logits_to_keep, None)
            if isinstance(logits_to_keep, int)
            else logits_to_keep
        )

        token_types = model_kwargs.get("token_types", None)
        logits = None
        if return_logits and not (labels is not None and token_types is not None):
            logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            if token_types is not None:
                token_types = token_types.to(hidden_states.device)
                labels = labels.to(hidden_states.device)
                text_loss = hidden_states.sum() * 0.0
                valid_text_mask = (
                    ((token_types == 0) | (token_types == 2))
                    & (labels != -100)
                    & compute_text_loss
                )
                text_token_count = valid_text_mask.sum()
                if compute_text_loss and self.lambda_text > 0.0:
                    text_hidden = hidden_states[valid_text_mask]
                    text_targets = labels[valid_text_mask]
                    text_logits = self.lm_head(text_hidden)
                    text_loss = F.cross_entropy(
                        text_logits,
                        text_targets,
                        reduction="sum",
                    ) / text_token_count.clamp_min(1).to(text_logits.dtype)
                if not compute_image_loss:
                    image_loss = self._zero_image_module_loss(hidden_states)
                    image_token_count = torch.zeros(
                        (), device=hidden_states.device, dtype=torch.long
                    )
                elif image_span_table_arg is None:
                    raise ValueError(
                        "Caption image-flow training requires image_span_table from "
                        "the collator; GPU span discovery is intentionally unsupported."
                    )
                elif image_latents is None:
                    raise ValueError(
                        "image_latents must be provided for continuous image flow loss."
                    )
                elif image_latents.shape[-1] != self.image_latent_dim:
                    raise ValueError(
                        f"image_latents last dimension ({image_latents.shape[-1]}) must match "
                        f"config.image_latent_dim ({self.image_latent_dim})."
                    )
                else:
                    span_table = image_span_table_arg.to(
                        device=hidden_states.device,
                        dtype=torch.long,
                    )
                    if span_table.ndim != 2 or span_table.shape[1] < 4:
                        raise ValueError(
                            "image_span_table must have shape [num_images, >=4], got "
                            f"{tuple(span_table.shape)}"
                        )
                    if span_table.shape[0] == 0:
                        raise ValueError("caption batch contains no image spans")

                    image_tokens_per_img = int(self.config.image_tokens_per_img)
                    rows = span_table[:, 0]
                    starts = span_table[:, 2]
                    offsets = torch.arange(
                        image_tokens_per_img,
                        device=hidden_states.device,
                        dtype=torch.long,
                    ).unsqueeze(0)
                    token_indices = starts.unsqueeze(1) + offsets

                    clean_image_latents = clean_image_latents.to(hidden_states.device)
                    context_for_loss = (
                        clean_image_latents
                        if context_image_latents is None
                        else context_image_latents.to(hidden_states.device)
                    )
                    image_targets = clean_image_latents[rows.unsqueeze(1), token_indices]
                    image_context_latents = context_for_loss[
                        rows.unsqueeze(1), token_indices
                    ]
                    selected_hidden_states = torch.index_select(hidden_states, 0, rows)
                    hidden_gather_indices = token_indices.unsqueeze(-1).expand(
                        -1, -1, hidden_states.shape[-1]
                    )
                    image_hidden_states = torch.gather(
                        selected_hidden_states,
                        dim=1,
                        index=hidden_gather_indices,
                    )
                    image_conditions = self._prepare_image_flow_condition(
                        image_hidden_states
                    )
                    image_content_conditions = None
                    if use_x0_content_condition:
                        x0_hidden_states = outputs.get(
                            "x0_last_hidden_state", None
                        )
                        if x0_hidden_states is None:
                            raise RuntimeError(
                                "X0-content flow contract requested but the "
                                "backbone did not return X0 hidden states"
                            )
                        selected_x0_hidden_states = torch.index_select(
                            x0_hidden_states,
                            0,
                            rows,
                        )
                        x0_hidden_gather_indices = token_indices.unsqueeze(
                            -1
                        ).expand(-1, -1, x0_hidden_states.shape[-1])
                        image_x0_hidden_states = torch.gather(
                            selected_x0_hidden_states,
                            dim=1,
                            index=x0_hidden_gather_indices,
                        )
                        image_content_conditions = (
                            self._prepare_image_flow_condition(
                                image_x0_hidden_states
                            )
                        )
                    flow_sigma = model_kwargs.get("flow_sigma", None)
                    if flow_sigma is None:
                        image_sigmas = offsets.expand(span_table.shape[0], -1).float()
                    else:
                        flow_sigma = flow_sigma.to(
                            device=hidden_states.device,
                            dtype=torch.float32,
                        )
                        image_sigmas = flow_sigma[rows.unsqueeze(1), token_indices]
                    if image_local_positions_arg is None:
                        image_positions_for_flow = offsets.expand(
                            span_table.shape[0], -1
                        )
                    else:
                        local_positions = image_local_positions_arg.to(
                            device=hidden_states.device,
                            dtype=torch.long,
                        )
                        image_positions_for_flow = local_positions[
                            rows.unsqueeze(1), token_indices
                        ]
                    image_loss_mask = None
                    if image_loss_mask_arg is not None:
                        full_loss_mask = image_loss_mask_arg.to(
                            device=hidden_states.device,
                            dtype=torch.bool,
                        )
                        image_loss_mask = full_loss_mask[
                            rows.unsqueeze(1), token_indices
                        ]

                    if self.image_flow_batch_mul > 1:
                        repeats = self.image_flow_batch_mul
                        share_content = use_x0_content_condition and bool(
                            getattr(self.config, "image_flow_share_content", False)
                        )
                        image_targets = image_targets.repeat(repeats, 1, 1)
                        if not share_content:
                            image_context_latents = image_context_latents.repeat(
                                repeats, 1, 1
                            )
                        image_conditions = image_conditions.repeat(repeats, 1, 1)
                        if image_content_conditions is not None and not share_content:
                            image_content_conditions = (
                                image_content_conditions.repeat(repeats, 1, 1)
                            )
                        image_sigmas = image_sigmas.repeat(repeats, 1)
                        image_positions_for_flow = image_positions_for_flow.repeat(
                            repeats, 1
                        )
                        if image_loss_mask is not None:
                            image_loss_mask = image_loss_mask.repeat(repeats, 1)
                    image_flow_kwargs = dict(
                        target=image_targets,
                        z=image_conditions,
                        mask=image_loss_mask,
                        sigma=image_sigmas,
                        image_positions=image_positions_for_flow,
                        context_latents=image_context_latents,
                        record_stats=record_flow_stats,
                    )
                    if image_content_conditions is not None:
                        image_flow_kwargs["context_conditions"] = (
                            image_content_conditions
                        )
                    image_loss = self.image_flow_head(**image_flow_kwargs)
                    image_token_count = (
                        image_loss_mask.sum()
                        if image_loss_mask is not None
                        else torch.tensor(
                            image_targets.shape[0] * image_targets.shape[1],
                            device=hidden_states.device,
                            dtype=torch.long,
                        )
                    )
                loss = (
                    self.lambda_text * text_loss
                    + self.lambda_image * image_loss
                )
            else:
                loss = self.loss_function(
                    logits.view(-1, logits.size(-1)), labels.view(-1), ignore_index=-100
                )

        output = CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )
        output["last_hidden_state"] = hidden_states
        gate_stats_fn = getattr(
            self.model,
            "backbone_attention_gate_stats",
            None,
        )
        backbone_gate_stats = gate_stats_fn() if gate_stats_fn is not None else {}
        if backbone_gate_stats:
            output["backbone_gate_stats"] = backbone_gate_stats
        if token_types is not None and loss is not None:
            output["per_modality_loss"] = {
                "text_loss": text_loss.detach(),
                "image_loss": image_loss.detach(),
            }
            if return_per_modality_loss_graph:
                # Cold-path diagnostic hook used by the standalone gradient
                # probe.  The normal training/validation API remains detached
                # so callers cannot accidentally retain both task graphs.
                output["per_modality_loss_graph"] = {
                    "text_loss": text_loss,
                    "image_loss": image_loss,
                }
            output["per_modality_count"] = {
                "text_tokens": text_token_count.detach(),
                "image_tokens": image_token_count.detach(),
            }
            flow_debug_stats = {
                key: value.detach()
                for key, value in self.image_flow_head.last_forward_stats.items()
                if isinstance(value, torch.Tensor)
            }
            output["flow_debug_stats"] = flow_debug_stats
        return output

    def loss_function(self, logits, labels, ignore_index, reduction="mean"):
        return F.cross_entropy(
            logits.view(-1, logits.size(-1)),
            labels.view(-1),
            ignore_index=ignore_index,
            reduction=reduction,
        )



class Qwen3ForSequenceClassification(
    GenericForSequenceClassification, Qwen3PreTrainedModel
):
    pass


class Qwen3ForTokenClassification(GenericForTokenClassification, Qwen3PreTrainedModel):
    pass


class Qwen3ForQuestionAnswering(GenericForQuestionAnswering, Qwen3PreTrainedModel):
    base_model_prefix = (
        "transformer"  # For BC, where `transformer` was used instead of `model`
    )


__all__ = [
    "LEGACY_FLOW_CONDITION_CONTRACT",
    "Qwen3ForCausalLM",
    "Qwen3ForQuestionAnswering",
    "Qwen3PreTrainedModel",
    "Qwen3Model",
    "Qwen3ForSequenceClassification",
    "Qwen3ForTokenClassification",
    "X0_CONTENT_FLOW_CONDITION_CONTRACT",
    "X0ContentFlowLoss",
]
